var h;h||(h=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca="object"===typeof window,da="function"===typeof importScripts,ea="object"===typeof process&&"function"===typeof require&&!ca&&!da,fa=!ca&&!ea&&!da;
if(ea){h.print||(h.print=function(a){process.stdout.write(a+"\n")});h.printErr||(h.printErr=function(a){process.stderr.write(a+"\n")});var ga=require("fs"),ha=require("path");h.read=function(a,b){a=ha.normalize(a);var c=ga.readFileSync(a);c||a==ha.resolve(a)||(a=path.join(__dirname,"..","src",a),c=ga.readFileSync(a));c&&!b&&(c=c.toString());return c};h.readBinary=function(a){a=h.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};h.load=function(a){ia(read(a))};h.thisProgram||(h.thisProgram=
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");h.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;});h.inspect=function(){return"[Emscripten Module object]"}}else if(fa)h.print||(h.print=print),"undefined"!=typeof printErr&&(h.printErr=printErr),h.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},h.readBinary=function(a){if("function"===
typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?h.arguments=scriptArgs:"undefined"!=typeof arguments&&(h.arguments=arguments),eval("if (typeof gc === 'function' && gc.toString().indexOf('[native code]') > 0) var gc = undefined");else if(ca||da)h.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},"undefined"!=typeof arguments&&(h.arguments=arguments),"undefined"!==
typeof console?(h.print||(h.print=function(a){console.log(a)}),h.printErr||(h.printErr=function(a){console.log(a)})):h.print||(h.print=function(){}),da&&(h.load=importScripts),"undefined"===typeof h.setWindowTitle&&(h.setWindowTitle=function(a){document.title=a});else throw"Unknown runtime environment. Where are we?";function ia(a){eval.call(null,a)}!h.load&&h.read&&(h.load=function(a){ia(h.read(a))});h.print||(h.print=function(){});h.printErr||(h.printErr=h.print);h.arguments||(h.arguments=[]);
h.thisProgram||(h.thisProgram="./this.program");h.print=h.print;h.W=h.printErr;h.preRun=[];h.postRun=[];for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);
var p={pb:function(a){ka=a},cb:function(){return ka},ua:function(){return ma},ba:function(a){ma=a},La:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?p.J:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},bb:function(a){return Math.max(p.La(a),p.J)},sd:16,Nd:function(a,b){"double"===b||"i64"===b?a&7&&(assert(4===(a&7)),a+=4):assert(0===(a&3));return a},
Bd:function(a,b,c){return c||"i64"!=a&&"double"!=a?a?Math.min(b||(a?p.bb(a):0),p.J):Math.min(b,8):8},L:function(a,b,c){return c&&c.length?(c.splice||(c=Array.prototype.slice.call(c)),c.splice(0,0,b),h["dynCall_"+a].apply(null,c)):h["dynCall_"+a].call(null,b)},Z:[],Xa:function(a){for(var b=0;b<p.Z.length;b++)if(!p.Z[b])return p.Z[b]=a,2*(1+b);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},lb:function(a){p.Z[(a-2)/2]=null},O:function(a){p.O.ta||
(p.O.ta={});p.O.ta[a]||(p.O.ta[a]=1,h.W(a))},ma:{},Ed:function(a,b){assert(b);p.ma[b]||(p.ma[b]={});var c=p.ma[b];c[a]||(c[a]=function(){return p.L(b,a,arguments)});return c[a]},Cd:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},aa:function(a){var b=ma;ma=ma+a|0;ma=ma+15&-16;return b},Sa:function(a){var b=na;na=na+a|0;na=na+15&-16;return b},R:function(a){var b=oa;oa=oa+a|0;oa=oa+15&-16;if(a=oa>=pa)u("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+
pa+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "),a=!0;return a?(oa=b,0):b},ja:function(a,b){return Math.ceil(a/(b?b:16))*(b?b:16)},Kd:function(a,b,c){return c?+(a>>>0)+4294967296*+(b>>>0):+(a>>>0)+4294967296*+(b|0)},Ba:8,J:4,td:0};h.Runtime=p;p.addFunction=p.Xa;
p.removeFunction=p.lb;var qa=!1,ra,sa,ka;function assert(a,b){a||u("Assertion failed: "+b)}function ta(a){var b=h["_"+a];if(!b)try{b=eval("_"+a)}catch(c){}assert(b,"Cannot call unknown function "+a+" (perhaps LLVM optimizations or closure removed it?)");return b}var ua,va;
(function(){function a(a){a=a.toString().match(e).slice(1);return{arguments:a[0],body:a[1],returnValue:a[2]}}var b={stackSave:function(){p.ua()},stackRestore:function(){p.ba()},arrayToC:function(a){var b=p.aa(a.length);wa(a,b);return b},stringToC:function(a){var b=0;null!==a&&void 0!==a&&0!==a&&(b=p.aa((a.length<<2)+1),xa(a,b));return b}},c={string:b.stringToC,array:b.arrayToC};va=function(a,b,e,f,g){a=ta(a);var r=[],J=0;if(f)for(var I=0;I<f.length;I++){var R=c[e[I]];R?(0===J&&(J=p.ua()),r[I]=R(f[I])):
r[I]=f[I]}e=a.apply(null,r);"string"===b&&(e=ya(e));if(0!==J){if(g&&g.async){EmterpreterAsync.vd.push(function(){p.ba(J)});return}p.ba(J)}return e};var e=/^function\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/,f={},g;for(g in b)b.hasOwnProperty(g)&&(f[g]=a(b[g]));ua=function(b,c,e){e=e||[];var g=ta(b);b=e.every(function(a){return"number"===a});var E="string"!==c;if(E&&b)return g;var r=e.map(function(a,b){return"$"+b});c="(function("+r.join(",")+") {";var J=e.length;if(!b){c+="var stack = "+
f.stackSave.body+";";for(var I=0;I<J;I++){var R=r[I],S=e[I];"number"!==S&&(S=f[S+"ToC"],c+="var "+S.arguments+" = "+R+";",c+=S.body+";",c+=R+"="+S.returnValue+";")}}e=a(function(){return g}).returnValue;c+="var ret = "+e+"("+r.join(",")+");";E||(e=a(function(){return ya}).returnValue,c+="ret = "+e+"(ret);");b||(c+=f.stackRestore.body.replace("()","(stack)")+";");return eval(c+"return ret})")}})();h.ccall=va;h.cwrap=ua;
function za(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":z[a>>0]=b;break;case "i8":z[a>>0]=b;break;case "i16":Aa[a>>1]=b;break;case "i32":G[a>>2]=b;break;case "i64":sa=[b>>>0,(ra=b,1<=+Ba(ra)?0<ra?(Ga(+Ha(ra/4294967296),4294967295)|0)>>>0:~~+Ia((ra-+(~~ra>>>0))/4294967296)>>>0:0)];G[a>>2]=sa[0];G[a+4>>2]=sa[1];break;case "float":Ja[a>>2]=b;break;case "double":Ka[a>>3]=b;break;default:u("invalid type for setValue: "+c)}}h.setValue=za;
function La(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return z[a>>0];case "i8":return z[a>>0];case "i16":return Aa[a>>1];case "i32":return G[a>>2];case "i64":return G[a>>2];case "float":return Ja[a>>2];case "double":return Ka[a>>3];default:u("invalid type for setValue: "+b)}return null}h.getValue=La;h.ALLOC_NORMAL=0;h.ALLOC_STACK=1;h.ALLOC_STATIC=2;h.ALLOC_DYNAMIC=3;h.ALLOC_NONE=4;
function Ma(a,b,c,e){var f,g;"number"===typeof a?(f=!0,g=a):(f=!1,g=a.length);var k="string"===typeof b?b:null;c=4==c?e:[Na,p.aa,p.Sa,p.R][void 0===c?2:c](Math.max(g,k?1:b.length));if(f){e=c;assert(0==(c&3));for(a=c+(g&-4);e<a;e+=4)G[e>>2]=0;for(a=c+g;e<a;)z[e++>>0]=0;return c}if("i8"===k)return a.subarray||a.slice?M.set(a,c):M.set(new Uint8Array(a),c),c;e=0;for(var l,q;e<g;){var m=a[e];"function"===typeof m&&(m=p.Fd(m));f=k||b[e];0===f?e++:("i64"==f&&(f="i32"),za(c+e,m,f),q!==f&&(l=p.La(f),q=f),
e+=l)}return c}h.allocate=Ma;h.getMemory=function(a){return Oa?"undefined"!==typeof Pa&&!Pa.F||!Qa?p.R(a):Na(a):p.Sa(a)};function ya(a,b){if(0===b||!a)return"";for(var c=0,e,f=0;;){e=M[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,M.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return h.UTF8ToString(a)}h.Pointer_stringify=ya;
h.AsciiToString=function(a){for(var b="";;){var c=z[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}};h.stringToAscii=function(a,b){return Ra(a,b,!1)};
function Sa(a,b){for(var c,e,f,g,k,l,q="";;){c=a[b++];if(!c)return q;c&128?(e=a[b++]&63,192==(c&224)?q+=String.fromCharCode((c&31)<<6|e):(f=a[b++]&63,224==(c&240)?c=(c&15)<<12|e<<6|f:(g=a[b++]&63,240==(c&248)?c=(c&7)<<18|e<<12|f<<6|g:(k=a[b++]&63,248==(c&252)?c=(c&3)<<24|e<<18|f<<12|g<<6|k:(l=a[b++]&63,c=(c&1)<<30|e<<24|f<<18|g<<12|k<<6|l))),65536>c?q+=String.fromCharCode(c):(c-=65536,q+=String.fromCharCode(55296|c>>10,56320|c&1023)))):q+=String.fromCharCode(c)}}h.UTF8ArrayToString=Sa;
h.UTF8ToString=function(a){return Sa(M,a)};
function Ta(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);55296<=k&&57343>=k&&(k=65536+((k&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=k){if(c>=e)break;b[c++]=k}else{if(2047>=k){if(c+1>=e)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++]=224|k>>12}else{if(2097151>=k){if(c+3>=e)break;b[c++]=240|k>>18}else{if(67108863>=k){if(c+4>=e)break;b[c++]=248|k>>24}else{if(c+5>=e)break;b[c++]=252|k>>30;b[c++]=128|k>>24&63}b[c++]=128|k>>18&63}b[c++]=128|
k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}h.stringToUTF8Array=Ta;h.stringToUTF8=function(a,b,c){return Ta(a,M,b,c)};function Ua(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}h.lengthBytesUTF8=Ua;h.UTF16ToString=function(a){for(var b=0,c="";;){var e=Aa[a+2*b>>1];if(0==e)return c;++b;c+=String.fromCharCode(e)}};
h.stringToUTF16=function(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Aa[b>>1]=a.charCodeAt(f),b+=2;Aa[b>>1]=0;return b-e};h.lengthBytesUTF16=function(a){return 2*a.length};h.UTF32ToString=function(a){for(var b=0,c="";;){var e=G[a+4*b>>2];if(0==e)return c;++b;65536<=e?(e=e-65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023)):c+=String.fromCharCode(e)}};
h.stringToUTF32=function(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g)var k=a.charCodeAt(++f),g=65536+((g&1023)<<10)|k&1023;G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-e};h.lengthBytesUTF32=function(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b};
function Va(a){function b(c,e,f){e=e||Infinity;var g="",k=[],d;if("N"===a[l]){l++;"K"===a[l]&&l++;for(d=[];"E"!==a[l];)if("S"===a[l]){l++;var r=a.indexOf("_",l);d.push(m[a.substring(l,r)||0]||"?");l=r+1}else if("C"===a[l])d.push(d[d.length-1]),l+=2;else{var r=parseInt(a.substr(l)),W=r.toString().length;if(!r||!W){l--;break}var D=a.substr(l+W,r);d.push(D);m.push(D);l+=W+r}l++;d=d.join("::");e--;if(0===e)return c?[d]:d}else if(("K"===a[l]||E&&"L"===a[l])&&l++,r=parseInt(a.substr(l)))W=r.toString().length,
d=a.substr(l+W,r),l+=W+r;E=!1;"I"===a[l]?(l++,r=b(!0),W=b(!0,1,!0),g+=W[0]+" "+d+"<"+r.join(", ")+">"):g=d;a:for(;l<a.length&&0<e--;)if(d=a[l++],d in q)k.push(q[d]);else switch(d){case "P":k.push(b(!0,1,!0)[0]+"*");break;case "R":k.push(b(!0,1,!0)[0]+"&");break;case "L":l++;r=a.indexOf("E",l)-l;k.push(a.substr(l,r));l+=r+2;break;case "A":r=parseInt(a.substr(l));l+=r.toString().length;if("_"!==a[l])throw"?";l++;k.push(b(!0,1,!0)[0]+" ["+r+"]");break;case "E":break a;default:g+="?"+d;break a}f||1!==
k.length||"void"!==k[0]||(k=[]);return c?(g&&k.push(g+"?"),k):g+("("+k.join(", ")+")")}var c=!!h.___cxa_demangle;if(c)try{var e=Na(a.length);xa(a.substr(1),e);var f=Na(4),g=h.___cxa_demangle(e,0,0,f);if(0===La(f,"i32")&&g)return ya(g)}catch(k){}finally{e&&Wa(e),f&&Wa(f),g&&Wa(g)}var l=3,q={v:"void",b:"bool",c:"char",s:"short",i:"int",l:"long",f:"float",d:"double",w:"wchar_t",a:"signed char",h:"unsigned char",t:"unsigned short",j:"unsigned int",m:"unsigned long",x:"long long",y:"unsigned long long",
z:"..."},m=[],E=!0,e=a;try{if("Object._main"==a||"_main"==a)return"main()";"number"===typeof a&&(a=ya(a));if("_"!==a[0]||"_"!==a[1]||"Z"!==a[2])return a;switch(a[3]){case "n":return"operator new()";case "d":return"operator delete()"}e=b()}catch(r){e+="?"}0<=e.indexOf("?")&&!c&&p.O("warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return e}
function Xa(){return Ya().replace(/__Z[\w\d_]+/g,function(a){var b=Va(a);return a===b?a:a+" ["+b+"]"})}function Ya(){var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack)return"(no stack trace available)"}return a.stack.toString()}h.stackTrace=function(){return Xa()};function Za(){var a=oa;0<a%4096&&(a+=4096-a%4096);return a}
for(var z,M,Aa,$a,G,ab,Ja,Ka,bb=0,na=0,Oa=!1,cb=0,ma=0,eb=0,fb=0,oa=0,gb=h.TOTAL_STACK||5242880,pa=h.TOTAL_MEMORY||16777216,hb=65536;hb<pa||hb<2*gb;)hb=16777216>hb?2*hb:hb+16777216;hb!==pa&&(pa=hb);assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&!!(new Int32Array(1)).subarray&&!!(new Int32Array(1)).set,"JS engine does not provide full typed array support");var buffer;buffer=new ArrayBuffer(pa);z=new Int8Array(buffer);Aa=new Int16Array(buffer);G=new Int32Array(buffer);
M=new Uint8Array(buffer);$a=new Uint16Array(buffer);ab=new Uint32Array(buffer);Ja=new Float32Array(buffer);Ka=new Float64Array(buffer);G[0]=255;assert(255===M[0]&&0===M[3],"Typed arrays 2 must be run on a little-endian system");h.HEAP=void 0;h.buffer=buffer;h.HEAP8=z;h.HEAP16=Aa;h.HEAP32=G;h.HEAPU8=M;h.HEAPU16=$a;h.HEAPU32=ab;h.HEAPF32=Ja;h.HEAPF64=Ka;
function ib(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Za;"number"===typeof c?void 0===b.X?p.L("v",c):p.L("vi",c,[b.X]):c(void 0===b.X?null:b.X)}}}var jb=[],kb=[],lb=[],mb=[],nb=[],Qa=!1;function ob(a){jb.unshift(a)}h.addOnPreRun=ob;h.addOnInit=function(a){kb.unshift(a)};h.addOnPreMain=function(a){lb.unshift(a)};h.addOnExit=function(a){mb.unshift(a)};function pb(a){nb.unshift(a)}h.addOnPostRun=pb;
function qb(a,b,c){c=Array(0<c?c:Ua(a)+1);a=Ta(a,c,0,c.length);b&&(c.length=a);return c}h.intArrayFromString=qb;h.intArrayToString=function(a){for(var b=[],c=0;c<a.length;c++){var e=a[c];255<e&&(e&=255);b.push(String.fromCharCode(e))}return b.join("")};function xa(a,b,c){a=qb(a,c);for(c=0;c<a.length;)z[b+c>>0]=a[c],c+=1}h.writeStringToMemory=xa;function wa(a,b){for(var c=0;c<a.length;c++)z[b++>>0]=a[c]}h.writeArrayToMemory=wa;
function Ra(a,b,c){for(var e=0;e<a.length;++e)z[b++>>0]=a.charCodeAt(e);c||(z[b>>0]=0)}h.writeAsciiToMemory=Ra;Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(a,b){var c=a&65535,e=b&65535;return c*e+((a>>>16)*e+c*(b>>>16)<<16)|0});Math.Gd=Math.imul;Math.clz32||(Math.clz32=function(a){a=a>>>0;for(var b=0;32>b;b++)if(a&1<<31-b)return b;return 32});Math.xd=Math.clz32;var Ba=Math.abs,Ia=Math.ceil,Ha=Math.floor,Ga=Math.min,rb=0,sb=null,tb=null;
function ub(){rb++;h.monitorRunDependencies&&h.monitorRunDependencies(rb)}h.addRunDependency=ub;function vb(){rb--;h.monitorRunDependencies&&h.monitorRunDependencies(rb);if(0==rb&&(null!==sb&&(clearInterval(sb),sb=null),tb)){var a=tb;tb=null;a()}}h.removeRunDependency=vb;h.preloadedImages={};h.preloadedAudios={};var wb=null,bb=8,na=bb+2240;kb.push();var wb="zuc.asm.js.mem",yb=p.ja(Ma(12,"i8",2),8);assert(0==yb%8);h._i64Add=zb;h._memset=Ab;
function Bb(a,b){mb.push(function(){p.L("vi",a,[b])});Bb.level=mb.length}
var N={I:1,D:2,cd:3,$b:4,H:5,Aa:6,tb:7,xc:8,ea:9,Hb:10,va:11,od:11,Ua:12,da:13,Tb:14,Jc:15,fa:16,wa:17,pd:18,ha:19,ya:20,P:21,q:22,sc:23,Ta:24,Q:25,ld:26,Ub:27,Fc:28,ia:29,$c:30,lc:31,Tc:32,Qb:33,Xc:34,Bc:42,Xb:43,Ib:44,cc:45,dc:46,ec:47,kc:48,md:49,vc:50,bc:51,Nb:35,yc:37,zb:52,Cb:53,qd:54,tc:55,Db:56,Eb:57,Ob:35,Fb:59,Hc:60,wc:61,hd:62,Gc:63,Cc:64,Dc:65,Zc:66,zc:67,wb:68,dd:69,Jb:70,Uc:71,nc:72,Rb:73,Bb:74,Oc:76,Ab:77,Yc:78,fc:79,gc:80,jc:81,ic:82,hc:83,Ic:38,za:39,oc:36,ga:40,Pc:95,Sc:96,Mb:104,
uc:105,xb:97,Wc:91,Mc:88,Ec:92,ad:108,Lb:111,ub:98,Kb:103,rc:101,pc:100,jd:110,Vb:112,Wb:113,Zb:115,yb:114,Pb:89,mc:90,Vc:93,bd:94,vb:99,qc:102,ac:106,Kc:107,kd:109,nd:87,Sb:122,ed:116,Nc:95,Ac:123,Yb:84,Qc:75,Gb:125,Lc:131,Rc:130,gd:86},Cb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function Db(a){h.___errno_location&&(G[h.___errno_location()>>2]=a);return a}
function Eb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c--;c)a.unshift("..");return a}function Fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Eb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Hb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Ib(){var a=Array.prototype.slice.call(arguments,0);return Fb(a.join("/"))}function O(a,b){return Fb(a+"/"+b)}
function Jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Eb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Kb=[];function Lb(a,b){Kb[a]={input:[],output:[],N:b};Mb(a,Nb)}
var Nb={open:function(a){var b=Kb[a.g.rdev];if(!b)throw new T(N.ha);a.tty=b;a.seekable=!1},close:function(a){a.tty.N.flush(a.tty)},flush:function(a){a.tty.N.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.N.Ma)throw new T(N.Aa);for(var f=0,g=0;g<e;g++){var k;try{k=a.tty.N.Ma(a.tty)}catch(l){throw new T(N.H);}if(void 0===k&&0===f)throw new T(N.va);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.g.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.N.qa)throw new T(N.Aa);
for(var f=0;f<e;f++)try{a.tty.N.qa(a.tty,b[c+f])}catch(g){throw new T(N.H);}e&&(a.g.timestamp=Date.now());return f}},Ob={Ma:function(a){if(!a.input.length){var b=null;if(ea){var c=new Buffer(256),e=0,f=process.stdin.fd,g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}e=fs.readSync(f,c,0,256,null);g&&fs.closeSync(f);0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},qa:function(a,b){null===b||10===b?(h.print(Sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h.print(Sa(a.output,0)),a.output=[])}},Pb={qa:function(a,b){null===b||10===b?(h.printErr(Sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h.printErr(Sa(a.output,0)),a.output=[])}},U={B:null,u:function(){return U.createNode(null,
"/",16895,0)},createNode:function(a,b,c,e){if(24576===(c&61440)||4096===(c&61440))throw new T(N.I);U.B||(U.B={dir:{g:{C:U.k.C,p:U.k.p,lookup:U.k.lookup,T:U.k.T,rename:U.k.rename,unlink:U.k.unlink,rmdir:U.k.rmdir,readdir:U.k.readdir,symlink:U.k.symlink},stream:{G:U.n.G}},file:{g:{C:U.k.C,p:U.k.p},stream:{G:U.n.G,read:U.n.read,write:U.n.write,Ca:U.n.Ca,Oa:U.n.Oa,Qa:U.n.Qa}},link:{g:{C:U.k.C,p:U.k.p,readlink:U.k.readlink},stream:{}},Fa:{g:{C:U.k.C,p:U.k.p},stream:Qb}});c=Rb(a,b,c,e);Sb(c.mode)?(c.k=
U.B.dir.g,c.n=U.B.dir.stream,c.e={}):32768===(c.mode&61440)?(c.k=U.B.file.g,c.n=U.B.file.stream,c.o=0,c.e=null):40960===(c.mode&61440)?(c.k=U.B.link.g,c.n=U.B.link.stream):8192===(c.mode&61440)&&(c.k=U.B.Fa.g,c.n=U.B.Fa.stream);c.timestamp=Date.now();a&&(a.e[b]=c);return c},ab:function(a){if(a.e&&a.e.subarray){for(var b=[],c=0;c<a.o;++c)b.push(a.e[c]);return b}return a.e},Dd:function(a){return a.e?a.e.subarray?a.e.subarray(0,a.o):new Uint8Array(a.e):new Uint8Array},Ha:function(a,b){a.e&&a.e.subarray&&
b>a.e.length&&(a.e=U.ab(a),a.o=a.e.length);if(!a.e||a.e.subarray){var c=a.e?a.e.buffer.byteLength:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.e,a.e=new Uint8Array(b),0<a.o&&a.e.set(c.subarray(0,a.o),0))}else for(!a.e&&0<b&&(a.e=[]);a.e.length<b;)a.e.push(0)},mb:function(a,b){if(a.o!=b)if(0==b)a.e=null,a.o=0;else{if(!a.e||a.e.subarray){var c=a.e;a.e=new Uint8Array(new ArrayBuffer(b));c&&a.e.set(c.subarray(0,Math.min(b,a.o)))}else if(a.e||(a.e=[]),a.e.length>b)a.e.length=
b;else for(;a.e.length<b;)a.e.push(0);a.o=b}},k:{C:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;Sb(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.o:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.K=4096;b.blocks=Math.ceil(b.size/b.K);return b},p:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=
b.timestamp);void 0!==b.size&&U.mb(a,b.size)},lookup:function(){throw Tb[N.D];},T:function(a,b,c,e){return U.createNode(a,b,c,e)},rename:function(a,b,c){if(Sb(a.mode)){var e;try{e=Ub(b,c)}catch(f){}if(e)for(var g in e.e)throw new T(N.za);}delete a.parent.e[a.name];a.name=c;b.e[c]=a;a.parent=b},unlink:function(a,b){delete a.e[b]},rmdir:function(a,b){var c=Ub(a,b),e;for(e in c.e)throw new T(N.za);delete a.e[b]},readdir:function(a){var b=[".",".."],c;for(c in a.e)a.e.hasOwnProperty(c)&&b.push(c);return b},
symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new T(N.q);return a.link}},n:{read:function(a,b,c,e,f){var g=a.g.e;if(f>=a.g.o)return 0;a=Math.min(a.g.o-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){if(!e)return 0;a=a.g;a.timestamp=Date.now();if(b.subarray&&(!a.e||a.e.subarray)){if(g)return a.e=b.subarray(c,c+e),a.o=e;if(0===a.o&&0===
f)return a.e=new Uint8Array(b.subarray(c,c+e)),a.o=e;if(f+e<=a.o)return a.e.set(b.subarray(c,c+e),f),e}U.Ha(a,f+e);if(a.e.subarray&&b.subarray)a.e.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.e[f+g]=b[c+g];a.o=Math.max(a.o,f+e);return e},G:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.g.mode&61440)&&(b+=a.g.o);if(0>b)throw new T(N.q);return b},Ca:function(a,b,c){U.Ha(a.g,b+c);a.g.o=Math.max(a.g.o,b+c)},Oa:function(a,b,c,e,f,g,k){if(32768!==(a.g.mode&61440))throw new T(N.ha);c=a.g.e;if(k&
2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+e<a.g.o)c.subarray?c=c.subarray(f,f+e):c=Array.prototype.slice.call(c,f,f+e);a=!0;e=Na(e);if(!e)throw new T(N.Ua);b.set(c,e)}else a=!1,e=c.byteOffset;return{Od:e,ud:a}},Qa:function(a,b,c,e,f){if(32768!==(a.g.mode&61440))throw new T(N.ha);if(f&2)return 0;U.n.write(a,b,0,e,c,!1);return 0}}},X={$:!1,qb:function(){X.$=!!process.platform.match(/^win/)},u:function(a){assert(ea);return X.createNode(null,"/",X.Ka(a.pa.root),0)},createNode:function(a,b,c){if(!Sb(c)&&
32768!==(c&61440)&&40960!==(c&61440))throw new T(N.q);a=Rb(a,b,c);a.k=X.k;a.n=X.n;return a},Ka:function(a){var b;try{b=fs.lstatSync(a),X.$&&(b.mode=b.mode|(b.mode&146)>>1)}catch(c){if(!c.code)throw c;throw new T(N[c.code]);}return b.mode},A:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.u.pa.root);b.reverse();return Ib.apply(null,b)},Ia:{0:"r",1:"r+",2:"r+",64:"r",65:"r+",66:"r+",129:"rx+",193:"rx+",514:"w+",577:"w",578:"w+",705:"wx",706:"wx+",1024:"a",1025:"a",1026:"a+",
1089:"a",1090:"a+",1153:"ax",1154:"ax+",1217:"ax",1218:"ax+",4096:"rs",4098:"rs+"},Ya:function(a){a&=-32769;if(a in X.Ia)return X.Ia[a];throw new T(N.q);},k:{C:function(a){a=X.A(a);var b;try{b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new T(N[c.code]);}X.$&&!b.K&&(b.K=4096);X.$&&!b.blocks&&(b.blocks=(b.size+b.K-1)/b.K|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,K:b.K,blocks:b.blocks}},p:function(a,
b){var c=X.A(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new T(N[e.code]);}},lookup:function(a,b){var c=O(X.A(a),b),c=X.Ka(c);return X.createNode(a,b,c)},T:function(a,b,c,e){a=X.createNode(a,b,c,e);b=X.A(a);try{Sb(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new T(N[f.code]);}return a},rename:function(a,b,c){a=X.A(a);b=O(X.A(b),c);try{fs.renameSync(a,
b)}catch(e){if(!e.code)throw e;throw new T(N[e.code]);}},unlink:function(a,b){var c=O(X.A(a),b);try{fs.unlinkSync(c)}catch(e){if(!e.code)throw e;throw new T(N[e.code]);}},rmdir:function(a,b){var c=O(X.A(a),b);try{fs.rmdirSync(c)}catch(e){if(!e.code)throw e;throw new T(N[e.code]);}},readdir:function(a){a=X.A(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new T(N[b.code]);}},symlink:function(a,b,c){a=O(X.A(a),b);try{fs.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new T(N[e.code]);
}},readlink:function(a){var b=X.A(a);try{return b=fs.readlinkSync(b),b=Vb.relative(Vb.resolve(a.u.pa.root),b)}catch(c){if(!c.code)throw c;throw new T(N[c.code]);}}},n:{open:function(a){var b=X.A(a.g);try{32768===(a.g.mode&61440)&&(a.V=fs.openSync(b,X.Ya(a.flags)))}catch(c){if(!c.code)throw c;throw new T(N[c.code]);}},close:function(a){try{32768===(a.g.mode&61440)&&a.V&&fs.closeSync(a.V)}catch(b){if(!b.code)throw b;throw new T(N[b.code]);}},read:function(a,b,c,e,f){if(0===e)return 0;var g=new Buffer(e),
k;try{k=fs.readSync(a.V,g,0,e,f)}catch(l){throw new T(N[l.code]);}if(0<k)for(a=0;a<k;a++)b[c+a]=g[a];return k},write:function(a,b,c,e,f){b=new Buffer(b.subarray(c,c+e));var g;try{g=fs.writeSync(a.V,b,0,e,f)}catch(k){throw new T(N[k.code]);}return g},G:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.g.mode&61440))try{b+=fs.fstatSync(a.V).size}catch(e){throw new T(N[e.code]);}if(0>b)throw new T(N.q);return b}}};Ma(1,"i32*",2);Ma(1,"i32*",2);Ma(1,"i32*",2);
var Wb=null,Xb=[null],Yb=[],Zb=1,$b=null,ac=!0,bc={},T=null,Tb={};
function cc(a,b){a=Jb("/",a);b=b||{};if(!a)return{path:"",g:null};var c={Ja:!0,ra:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.ra)throw new T(N.ga);var c=Eb(a.split("/").filter(function(a){return!!a}),!1),f=Wb;e="/";for(var g=0;g<c.length;g++){var k=g===c.length-1;if(k&&b.parent)break;f=Ub(f,c[g]);e=O(e,c[g]);f.U&&(!k||k&&b.Ja)&&(f=f.U.root);if(!k||b.la)for(k=0;40960===(f.mode&61440);)if(f=dc(e),e=Jb(Gb(e),f),f=cc(e,{ra:b.ra}).g,40<k++)throw new T(N.ga);}return{path:e,g:f}}
function ec(a){for(var b;;){if(a===a.parent)return a=a.u.Pa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function fc(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%$b.length}function gc(a){var b=fc(a.parent.id,a.name);a.M=$b[b];$b[b]=a}function Ub(a,b){var c;if(c=(c=hc(a,"x"))?c:a.k.lookup?0:N.da)throw new T(c,a);for(c=$b[fc(a.id,b)];c;c=c.M){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return a.k.lookup(a,b)}
function Rb(a,b,c,e){ic||(ic=function(a,b,c,e){a||(a=this);this.parent=a;this.u=a.u;this.U=null;this.id=Zb++;this.name=b;this.mode=c;this.k={};this.n={};this.rdev=e},ic.prototype={},Object.defineProperties(ic.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},ib:{get:function(){return Sb(this.mode)}},hb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new ic(a,b,c,e);gc(a);return a}function Sb(a){return 16384===(a&61440)}var jc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function hc(a,b){if(ac)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return N.da}else return N.da;return 0}function kc(a,b){try{return Ub(a,b),N.wa}catch(c){}return hc(a,"wx")}
function lc(){var a;a=4096;for(var b=0;b<=a;b++)if(!Yb[b])return b;throw new T(N.Ta);}function mc(a){nc||(nc=function(){},nc.prototype={},Object.defineProperties(nc.prototype,{object:{get:function(){return this.g},set:function(a){this.g=a}},Id:{get:function(){return 1!==(this.flags&2097155)}},Jd:{get:function(){return 0!==(this.flags&2097155)}},Hd:{get:function(){return this.flags&1024}}}));var b=new nc,c;for(c in a)b[c]=a[c];a=b;b=lc();a.fd=b;return Yb[b]=a}
var Qb={open:function(a){a.n=Xb[a.g.rdev].n;a.n.open&&a.n.open(a)},G:function(){throw new T(N.ia);}};function Mb(a,b){Xb[a]={n:b}}function oc(a,b){var c="/"===b,e=!b,f;if(c&&Wb)throw new T(N.fa);if(!c&&!e){f=cc(b,{Ja:!1});b=f.path;f=f.g;if(f.U)throw new T(N.fa);if(!Sb(f.mode))throw new T(N.ya);}var e={type:a,pa:{},Pa:b,jb:[]},g=a.u(e);g.u=e;e.root=g;c?Wb=g:f&&(f.U=e,f.u&&f.u.jb.push(e))}
function pc(a,b,c){var e=cc(a,{parent:!0}).g;a=Hb(a);if(!a||"."===a||".."===a)throw new T(N.q);var f=kc(e,a);if(f)throw new T(f);if(!e.k.T)throw new T(N.I);return e.k.T(e,a,b,c)}function qc(a,b){b=(void 0!==b?b:438)&4095;b|=32768;return pc(a,b,0)}function rc(a,b){b=(void 0!==b?b:511)&1023;b|=16384;return pc(a,b,0)}function sc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return pc(a,b|8192,c)}
function tc(a,b){if(!Jb(a))throw new T(N.D);var c=cc(b,{parent:!0}).g;if(!c)throw new T(N.D);var e=Hb(b),f=kc(c,e);if(f)throw new T(f);if(!c.k.symlink)throw new T(N.I);return c.k.symlink(c,e,a)}function dc(a){a=cc(a).g;if(!a)throw new T(N.D);if(!a.k.readlink)throw new T(N.q);return Jb(ec(a.parent),a.k.readlink(a))}function uc(a,b){var c;"string"===typeof a?c=cc(a,{la:!0}).g:c=a;if(!c.k.p)throw new T(N.I);c.k.p(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function vc(a,b){var c;if(""===a)throw new T(N.D);var e;if("string"===typeof b){if(e=jc[b],"undefined"===typeof e)throw Error("Unknown file open mode: "+b);}else e=b;b=e;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;var f;if("object"===typeof a)f=a;else{a=Fb(a);try{f=cc(a,{la:!(b&131072)}).g}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new T(N.wa);}else f=pc(a,c,0),e=!0;if(!f)throw new T(N.D);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!Sb(f.mode))throw new T(N.ya);if(!e&&(f?40960===(f.mode&
61440)?c=N.ga:Sb(f.mode)&&(0!==(b&2097155)||b&512)?c=N.P:(c=["r","w","rw"][b&3],b&512&&(c+="w"),c=hc(f,c)):c=N.D,c))throw new T(c);if(b&512){c=f;var k;"string"===typeof c?k=cc(c,{la:!0}).g:k=c;if(!k.k.p)throw new T(N.I);if(Sb(k.mode))throw new T(N.P);if(32768!==(k.mode&61440))throw new T(N.q);if(c=hc(k,"w"))throw new T(c);k.k.p(k,{size:0,timestamp:Date.now()})}b&=-641;f=mc({g:f,path:ec(f),flags:b,seekable:!0,position:0,n:f.n,rb:[],error:!1});f.n.open&&f.n.open(f);!h.logReadFiles||b&1||(wc||(wc={}),
a in wc||(wc[a]=1,h.printErr("read file: "+a)));try{bc.onOpenFile&&(k=0,1!==(b&2097155)&&(k|=1),0!==(b&2097155)&&(k|=2),bc.onOpenFile(a,k))}catch(l){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return f}function xc(a){a.na&&(a.na=null);try{a.n.close&&a.n.close(a)}catch(b){throw b;}finally{Yb[a.fd]=null}}function yc(a,b,c){if(!a.seekable||!a.n.G)throw new T(N.ia);a.position=a.n.G(a,b,c);a.rb=[]}
function zc(a,b,c,e,f,g){if(0>e||0>f)throw new T(N.q);if(0===(a.flags&2097155))throw new T(N.ea);if(Sb(a.g.mode))throw new T(N.P);if(!a.n.write)throw new T(N.q);a.flags&1024&&yc(a,0,2);var k=!0;if("undefined"===typeof f)f=a.position,k=!1;else if(!a.seekable)throw new T(N.ia);b=a.n.write(a,b,c,e,f,g);k||(a.position+=b);try{if(a.path&&bc.onWriteToFile)bc.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+l.message)}return b}
function Ac(){T||(T=function(a,b){this.g=b;this.ob=function(a){this.S=a;for(var b in N)if(N[b]===a){this.code=b;break}};this.ob(a);this.message=Cb[a]},T.prototype=Error(),T.prototype.constructor=T,[N.D].forEach(function(a){Tb[a]=new T(a);Tb[a].stack="<generic error, no stack>"}))}var Bc;function Cc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Dc(a,b,c,e){a=O("string"===typeof a?a:ec(a),b);return qc(a,Cc(c,e))}
function Ec(a,b,c,e,f,g){a=b?O("string"===typeof a?a:ec(a),b):a;e=Cc(e,f);f=qc(a,e);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}uc(f,e|146);a=vc(f,"w");zc(a,c,0,c.length,0,g);xc(a);uc(f,e)}return f}
function Fc(a,b,c,e){a=O("string"===typeof a?a:ec(a),b);b=Cc(!!c,!!e);Fc.Na||(Fc.Na=64);var f=Fc.Na++<<8|0;Mb(f,{open:function(a){a.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(a,b,e,f){for(var m=0,E=0;E<f;E++){var r;try{r=c()}catch(J){throw new T(N.H);}if(void 0===r&&0===m)throw new T(N.va);if(null===r||void 0===r)break;m++;b[e+E]=r}m&&(a.g.timestamp=Date.now());return m},write:function(a,b,c,f){for(var m=0;m<f;m++)try{e(b[c+m])}catch(E){throw new T(N.H);}f&&(a.g.timestamp=
Date.now());return m}});return sc(a,b,f)}
function Gc(a){if(a.hb||a.ib||a.link||a.e)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(h.read)try{a.e=qb(h.read(a.url),!0),a.o=a.e.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Db(N.H);return b}var Hc={},ic,nc,wc,Ic=0;
function Jc(){Ic+=4;return G[Ic-4>>2]}function Kc(){var a;a=Jc();a=Yb[a];if(!a)throw new T(N.ea);return a}function Pa(a){Pa.F||(oa=Za(),Pa.F=!0,assert(p.R),Pa.$a=p.R,p.R=function(){u("cannot dynamically allocate, sbrk now has control")});var b=oa;return 0==a||Pa.$a(a)?b:4294967295}h._memcpy=Lc;h._memmove=Mc;
function Nc(a,b){Oc=a;Pc=b;if(!Qc)return 1;if(0==a)Rc=function(){setTimeout(Sc,b)},Tc="timeout";else if(1==a)Rc=function(){Uc(Sc)},Tc="rAF";else if(2==a){if(!window.setImmediate){var c=[];window.addEventListener("message",function(a){a.source===window&&"__emcc"===a.data&&(a.stopPropagation(),c.shift()())},!0);window.setImmediate=function(a){c.push(a);window.postMessage("__emcc","*")}}Rc=function(){window.setImmediate(Sc)};Tc="immediate"}return 0}
function Xc(a,b,c,e,f){h.noExitRuntime=!0;assert(!Qc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Qc=a;Yc=e;var g=Zc;Sc=function(){if(!qa)if(0<$c.length){var b=Date.now(),c=$c.shift();c.Za(c.X);if(ad){var f=ad,m=0==f%1?f-1:Math.floor(f);ad=c.yd?m:(8*f+(m+.5))/9}console.log('main loop blocker "'+c.name+'" took '+(Date.now()-b)+" ms");bd();setTimeout(Sc,0)}else g<
Zc||(cd=cd+1|0,1==Oc&&1<Pc&&0!=cd%Pc?Rc():("timeout"===Tc&&h.ka&&(h.W("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),Tc=""),dd(function(){"undefined"!==typeof e?p.L("vi",a,[e]):p.L("v",a)}),g<Zc||("object"===typeof SDL&&SDL.audio&&SDL.audio.kb&&SDL.audio.kb(),Rc())))};f||(b&&0<b?Nc(0,1E3/b):Nc(1,1),Rc());if(c)throw"SimulateInfiniteLoop";
}var Rc=null,Tc="",Zc=0,Qc=null,Yc=0,Oc=0,Pc=0,cd=0,$c=[];function bd(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=ad,c=ed.Ad;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}}function dd(a){if(!(qa||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof ja)return;b&&"object"===typeof b&&b.stack&&h.W("exception thrown: "+[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}var ed={},Sc,ad,fd=!1,gd=!1,hd=[];
function id(){function a(){gd=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}h.preloadPlugins||(h.preloadPlugins=[]);if(!jd){jd=!0;try{kd=!0}catch(b){kd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}ld="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:kd?null:console.log("warning: no BlobBuilder");md="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ra||"undefined"!==typeof md||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ra=!0);h.preloadPlugins.push({canHandle:function(a){return!h.Ra&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,c,k){var l=null;if(kd)try{l=new Blob([a],{type:nd(b)}),l.size!==a.length&&(l=new Blob([(new Uint8Array(a)).buffer],{type:nd(b)}))}catch(q){p.O("Blob constructor present but fails: "+
q+"; falling back to blob builder")}l||(l=new ld,l.append((new Uint8Array(a)).buffer),l=l.getBlob());var m=md.createObjectURL(l),E=new Image;E.onload=function(){assert(E.complete,"Image "+b+" could not be decoded");var k=document.createElement("canvas");k.width=E.width;k.height=E.height;k.getContext("2d").drawImage(E,0,0);h.preloadedImages[b]=k;md.revokeObjectURL(m);c&&c(a)};E.onerror=function(){console.log("Image "+m+" could not be decoded");k&&k()};E.src=m}});h.preloadPlugins.push({canHandle:function(a){return!h.Md&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,c,k){function l(k){m||(m=!0,h.preloadedAudios[b]=k,c&&c(a))}function q(){m||(m=!0,h.preloadedAudios[b]=new Audio,k&&k())}var m=!1;if(kd){try{var E=new Blob([a],{type:nd(b)})}catch(r){return q()}var E=md.createObjectURL(E),J=new Audio;J.addEventListener("canplaythrough",function(){l(J)},!1);J.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var c="",g=0,k=0,
E=0;E<a.length;E++)for(g=g<<8|a[E],k+=8;6<=k;)var d=g>>k-6&63,k=k-6,c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d];2==k?(c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(g&3)<<4],c+="=="):4==k&&(c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(g&15)<<2],c+="=");J.src="data:audio/x-"+b.substr(-3)+";base64,"+c;l(J)}};J.src=E;od(function(){l(J)})}else return q()}});var c=h.canvas;c&&(c.sa=c.requestPointerLock||c.mozRequestPointerLock||
c.webkitRequestPointerLock||c.msRequestPointerLock||function(){},c.Ga=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},c.Ga=c.Ga.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&c.addEventListener("click",function(a){!gd&&
c.sa&&(c.sa(),a.preventDefault())},!1))}}function pd(a,b,c,e){if(b&&h.ka&&a==h.canvas)return h.ka;var f,g;if(b){g={antialias:!1,alpha:!1};if(e)for(var k in e)g[k]=e[k];if(g=GL.createContext(a,g))f=GL.getContext(g).rd;a.style.backgroundColor="black"}else f=a.getContext("2d");if(!f)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ka=f,b&&GL.Ld(g),h.Pd=b,hd.forEach(function(a){a()}),id());return f}
var qd=!1,rd=void 0,sd=void 0;
function td(a,b,c){function e(){fd=!1;var a=f.parentNode;(document.webkitFullScreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.mozFullscreenElement||document.fullScreenElement||document.fullscreenElement||document.msFullScreenElement||document.msFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.Ea=document.cancelFullScreen||document.mozCancelFullScreen||document.webkitCancelFullScreen||document.msExitFullscreen||document.exitFullscreen||function(){},
f.Ea=f.Ea.bind(document),rd&&f.sa(),fd=!0,sd&&ud()):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),sd&&vd());if(h.onFullScreen)h.onFullScreen(fd);wd(f)}rd=a;sd=b;xd=c;"undefined"===typeof rd&&(rd=!0);"undefined"===typeof sd&&(sd=!1);"undefined"===typeof xd&&(xd=null);var f=h.canvas;qd||(qd=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",
e,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.F=g.requestFullScreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.F({Qd:c}):g.F()}var yd=0;function zd(a){var b=Date.now();if(0===yd)yd=b+1E3/60;else for(;b+2>=yd;)yd+=1E3/60;b=Math.max(yd-b,0);setTimeout(a,b)}
function Uc(a){"undefined"===typeof window?zd(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||zd),window.requestAnimationFrame(a))}function od(a){h.noExitRuntime=!0;setTimeout(function(){qa||a()},1E4)}
function nd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function Ad(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)}
function Bd(a,b,c){Ad(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));vb()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});ub()}var Cd=[];function Dd(){var a=h.canvas;Cd.forEach(function(b){b(a.width,a.height)})}function ud(){if("undefined"!=typeof SDL){var a=ab[SDL.screen+0*p.J>>2];G[SDL.screen+0*p.J>>2]=a|8388608}Dd()}
function vd(){if("undefined"!=typeof SDL){var a=ab[SDL.screen+0*p.J>>2];G[SDL.screen+0*p.J>>2]=a&-8388609}Dd()}
function wd(a,b,c){b&&c?(a.sb=b,a.fb=c):(b=a.sb,c=a.fb);var e=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(e/f<h.forcedAspectRatio?e=Math.round(f*h.forcedAspectRatio):f=Math.round(e/h.forcedAspectRatio));if((document.webkitFullScreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.mozFullscreenElement||document.fullScreenElement||document.fullscreenElement||document.msFullScreenElement||document.msFullscreenElement||document.webkitCurrentFullScreenElement)===
a.parentNode&&"undefined"!=typeof screen)var g=Math.min(screen.width/e,screen.height/f),e=Math.round(e*g),f=Math.round(f*g);sd?(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||f!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var jd,kd,ld,md,xd;Ac();$b=Array(4096);oc(U,"/");rc("/tmp");rc("/home");rc("/home/web_user");
(function(){rc("/dev");Mb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});sc("/dev/null",259);Lb(1280,Ob);Lb(1536,Pb);sc("/dev/tty",1280);sc("/dev/tty1",1536);var a;if("undefined"!==typeof crypto){var b=new Uint8Array(1);a=function(){crypto.getRandomValues(b);return b[0]}}else a=ea?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};Fc("/dev","random",a);Fc("/dev","urandom",a);rc("/dev/shm");rc("/dev/shm/tmp")})();rc("/proc");rc("/proc/self");
rc("/proc/self/fd");oc({u:function(){var a=Rb("/proc/self","fd",16895,73);a.k={lookup:function(a,c){var e=Yb[+c];if(!e)throw new T(N.ea);var f={parent:null,u:{Pa:"fake"},k:{readlink:function(){return e.path}}};return f.parent=f}};return a}},"/proc/self/fd");
kb.unshift(function(){if(!h.noFSInit&&!Bc){assert(!Bc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Bc=!0;Ac();h.stdin=h.stdin;h.stdout=h.stdout;h.stderr=h.stderr;h.stdin?Fc("/dev","stdin",h.stdin):tc("/dev/tty","/dev/stdin");h.stdout?Fc("/dev","stdout",null,h.stdout):tc("/dev/tty","/dev/stdout");h.stderr?Fc("/dev","stderr",null,h.stderr):tc("/dev/tty1","/dev/stderr");
var a=vc("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=vc("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=vc("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});lb.push(function(){ac=!1});mb.push(function(){Bc=!1;var a=h._fflush;a&&a(0);for(a=0;a<Yb.length;a++){var b=Yb[a];b&&xc(b)}});h.FS_createFolder=function(a,b,c,e){a=O("string"===typeof a?a:ec(a),b);return rc(a,Cc(c,e))};
h.FS_createPath=function(a,b){a="string"===typeof a?a:ec(a);for(var c=b.split("/").reverse();c.length;){var e=c.pop();if(e){var f=O(a,e);try{rc(f)}catch(g){}a=f}}return f};h.FS_createDataFile=Ec;
h.FS_createPreloadedFile=function(a,b,c,e,f,g,k,l,q,m){function E(c){function E(c){m&&m();l||Ec(a,b,c,e,f,q);g&&g();vb()}var R=!1;h.preloadPlugins.forEach(function(a){!R&&a.canHandle(r)&&(a.handle(c,r,E,function(){k&&k();vb()}),R=!0)});R||E(c)}id();var r=b?Jb(O(a,b)):a;ub();"string"==typeof c?Bd(c,function(a){E(a)},k):E(c)};
h.FS_createLazyFile=function(a,b,c,e,f){var g,k;function l(){this.oa=!1;this.Y=[]}l.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.eb(a/this.chunkSize|0)[b]}};l.prototype.nb=function(a){this.eb=a};l.prototype.Da=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),e,f=1048576;(e=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===e||(f=b);var g=this;g.nb(function(a){var e=a*f,d=(a+1)*f-1,d=Math.min(d,b-1);if("undefined"===typeof g.Y[a]){var k=g.Y;if(e>d)throw Error("invalid range ("+e+", "+d+") or no bytes requested!");if(d>b-1)throw Error("only "+b+" bytes available! programmer error!");var l=new XMLHttpRequest;l.open("GET",c,!1);b!==f&&l.setRequestHeader("Range","bytes="+e+"-"+d);"undefined"!=typeof Uint8Array&&(l.responseType="arraybuffer");l.overrideMimeType&&l.overrideMimeType("text/plain; charset=x-user-defined");
l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);e=void 0!==l.response?new Uint8Array(l.response||[]):qb(l.responseText||"",!0);k[a]=e}if("undefined"===typeof g.Y[a])throw Error("doXHR failed!");return g.Y[a]});this.Wa=b;this.Va=f;this.oa=!0};if("undefined"!==typeof XMLHttpRequest){if(!da)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";g=new l;Object.defineProperty(g,
"length",{get:function(){this.oa||this.Da();return this.Wa}});Object.defineProperty(g,"chunkSize",{get:function(){this.oa||this.Da();return this.Va}});k=void 0}else k=c,g=void 0;var q=Dc(a,b,e,f);g?q.e=g:k&&(q.e=null,q.url=k);Object.defineProperty(q,"usedBytes",{get:function(){return this.e.length}});var m={};Object.keys(q.n).forEach(function(a){var b=q.n[a];m[a]=function(){if(!Gc(q))throw new T(N.H);return b.apply(null,arguments)}});m.read=function(a,b,c,e,f){if(!Gc(q))throw new T(N.H);a=a.g.e;if(f>=
a.length)return 0;e=Math.min(a.length-f,e);assert(0<=e);if(a.slice)for(var g=0;g<e;g++)b[c+g]=a[f+g];else for(g=0;g<e;g++)b[c+g]=a.get(f+g);return e};q.n=m;return q};h.FS_createLink=function(a,b,c){a=O("string"===typeof a?a:ec(a),b);return tc(c,a)};h.FS_createDevice=Fc;
h.FS_unlink=function(a){var b=cc(a,{parent:!0}).g,c=Hb(a),e=Ub(b,c),f;a:{try{f=Ub(b,c)}catch(g){f=g.S;break a}var k=hc(b,"wx");f=k?k:Sb(f.mode)?N.P:0}if(f)throw f===N.P&&(f=N.I),new T(f);if(!b.k.unlink)throw new T(N.I);if(e.U)throw new T(N.fa);try{bc.willDeletePath&&bc.willDeletePath(a)}catch(l){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+l.message)}b.k.unlink(b,c);b=fc(e.parent.id,e.name);if($b[b]===e)$b[b]=e.M;else for(b=$b[b];b;){if(b.M===e){b.M=e.M;break}b=
b.M}try{if(bc.onDeletePath)bc.onDeletePath(a)}catch(q){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+q.message)}};kb.unshift(function(){});mb.push(function(){});if(ea){var fs=require("fs"),Vb=require("path");X.qb()}h.requestFullScreen=function(a,b,c){td(a,b,c)};h.requestAnimationFrame=function(a){Uc(a)};h.setCanvasSize=function(a,b,c){wd(h.canvas,a,b);c||Dd()};h.pauseMainLoop=function(){Rc=null;Zc++};
h.resumeMainLoop=function(){Zc++;var a=Oc,b=Pc,c=Qc;Qc=null;Xc(c,0,!1,Yc,!0);Nc(a,b);Rc()};h.getUserMedia=function(){window.F||(window.F=navigator.getUserMedia||navigator.mozGetUserMedia);window.F(void 0)};h.createContext=function(a,b,c,e){return pd(a,b,c,e)};cb=ma=p.ja(na);Oa=!0;eb=cb+gb;fb=oa=p.ja(eb);assert(fb<pa,"TOTAL_MEMORY not big enough for stack");
var Ed=Ma([8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,
0,1,0,3,0,1,0,2,0,1,0],"i8",3);h.asmGlobalArg={Math:Math,Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array,Uint32Array:Uint32Array,Float32Array:Float32Array,Float64Array:Float64Array,NaN:NaN,Infinity:Infinity};
h.asmLibraryArg={abort:u,assert:assert,invoke_ii:function(a,b){try{return h.dynCall_ii(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;Y.setThrew(1,0)}},invoke_iiii:function(a,b,c,e){try{return h.dynCall_iiii(a,b,c,e)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;Y.setThrew(1,0)}},invoke_vi:function(a,b){try{h.dynCall_vi(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;Y.setThrew(1,0)}},_pthread_cleanup_pop:function(){assert(Bb.level==mb.length,"cannot pop if something else added meanwhile!");
mb.pop();Bb.level=mb.length},___lock:function(){},_emscripten_set_main_loop:Xc,_pthread_self:function(){return 0},_abort:function(){h.abort()},_emscripten_set_main_loop_timing:Nc,___syscall6:function(a,b){Ic=b;try{var c=Kc();xc(c);return 0}catch(e){return"undefined"!==typeof Hc&&e instanceof T||u(e),-e.S}},_sbrk:Pa,_time:function(a){var b=Date.now()/1E3|0;a&&(G[a>>2]=b);return b},___setErrNo:Db,_emscripten_memcpy_big:function(a,b,c){M.set(M.subarray(b,b+c),a);return a},___syscall54:function(a,b){Ic=
b;try{var c=Kc(),e=Jc();switch(e){case 21505:return c.tty?0:-N.Q;case 21506:return c.tty?0:-N.Q;case 21519:if(!c.tty)return-N.Q;var f=Jc();return G[f>>2]=0;case 21520:return c.tty?-N.q:-N.Q;case 21531:f=Jc();if(!c.n.gb)throw new T(N.Q);return c.n.gb(c,e,f);default:u("bad ioctl syscall "+e)}}catch(g){return"undefined"!==typeof Hc&&g instanceof T||u(g),-g.S}},___unlock:function(){},___syscall140:function(a,b){Ic=b;try{var c=Kc(),e=Jc(),f=Jc(),g=Jc(),k=Jc();assert(0===e);yc(c,f,k);G[g>>2]=c.position;
c.na&&0===f&&0===k&&(c.na=null);return 0}catch(l){return"undefined"!==typeof Hc&&l instanceof T||u(l),-l.S}},_pthread_cleanup_push:Bb,_sysconf:function(a){switch(a){case 30:return 4096;case 85:return hb/4096;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}Db(N.q);return-1},
___syscall146:function(a,b){Ic=b;try{var c=Kc(),e=Jc(),f;a:{for(var g=Jc(),k=0,l=0;l<g;l++){var q=zc(c,z,G[e+8*l>>2],G[e+(8*l+4)>>2],void 0);if(0>q){f=-1;break a}k+=q}f=k}return f}catch(m){return"undefined"!==typeof Hc&&m instanceof T||u(m),-m.S}},STACKTOP:ma,STACK_MAX:eb,tempDoublePtr:yb,ABORT:qa,cttz_i8:Ed};
var Y=function(a,b,c){function e(a){a=a|0;d[a+72>>2]=d[a+60>>2]<<1&-65536|d[a+56>>2]&65535;d[a+76>>2]=(d[a+36>>2]|0)>>>15|d[a+44>>2]<<16;d[a+80>>2]=(d[a+20>>2]|0)>>>15|d[a+28>>2]<<16;d[a+84>>2]=(d[a>>2]|0)>>>15|d[a+8>>2]<<16}function f(a){a=a|0;var b=0,c=0,e=0,f=0,g=0,k=0,e=a+64|0,g=d[e>>2]|0,c=a+68|0,k=d[c>>2]|0,b=(g^d[a+72>>2])+k|0,g=(d[a+76>>2]|0)+g|0,k=d[a+80>>2]^k,f=k>>>16;a=f|g<<16;f=(a<<2|g>>>14&3)^a^(a<<10|g>>>6&1023)^(a>>>14|f<<18)^(a>>>8|f<<24);a=g>>>16;g=k<<16|a;a=(g<<8|k>>>8&255)^g^(g<<
14|k>>>2&16383)^(g>>>10|a<<22)^(g>>>2|a<<30);d[e>>2]=(V[956+(f>>>16&255)>>0]|0)<<16|(V[700+(f>>>24)>>0]|0)<<24|(V[700+(f>>>8&255)>>0]|0)<<8|V[956+(f&255)>>0]|0;d[c>>2]=(V[956+(a>>>16&255)>>0]|0)<<16|(V[700+(a>>>24)>>0]|0)<<24|(V[700+(a>>>8&255)>>0]|0)<<8|V[956+(a&255)>>0]|0;return b|0}function g(a){a=a|0;var b=0,b=k(a)|0;S(a|0,a+4|0,60)|0;d[a+60>>2]=b}function k(a){a=a|0;var b=0,c=0,e=0,f=0,c=d[a>>2]|0,c=(c<<8&2147483392|c>>>23)+c|0,e=d[a+16>>2]|0,e=(c>>>31)+(e<<20&2146435072|e>>>11)|0,b=c+e|0,f=
d[a+40>>2]|0,f=((e+(c&2147483647)|0)>>>31)+(f<<21&2145386496|f>>>10)|0,c=b+f|0,e=d[a+52>>2]|0,e=((f+(b&2147483647)|0)>>>31)+(e<<17&2147352576|e>>>14)|0,b=c+e|0;a=d[a+60>>2]|0;a=((e+(c&2147483647)|0)>>>31)+(a<<15&2147450880|a>>>16)|0;return(b+a&2147483647)+((a+(b&2147483647)|0)>>>31)|0}function l(){var a=0,a=d[2]|0?d[(Od()|0)+60>>2]|0:56;return a|0}function q(a){a=a|0;4294963200<a>>>0&&(d[(l()|0)>>2]=0-a,a=-1);return a|0}function m(a){a=a|0;var b=0;if(a)b=r(a)|0;else{b=d[13]|0?m(d[13]|0)|0:0;Pd(36);
if(a=d[8]|0){do(d[a+20>>2]|0)>>>0>(d[a+28>>2]|0)>>>0&&(b|=r(a)|0),a=d[a+56>>2]|0;while(0!=(a|0))}Qd(36)}return b|0}function E(a,b,c){a=a|0;c=c|0;var e=0,f=0,g=0,k=0,l=0,w=0,t=0,m=0,v=0,r=0,x=0,A=0,A=D;D=D+48|0;v=A+16|0;m=A;e=A+32|0;r=a+28|0;f=d[r>>2]|0;d[e>>2]=f;x=a+20|0;f=(d[x>>2]|0)-f|0;d[e+4>>2]=f;d[e+8>>2]=b|0;d[e+12>>2]=c;w=a+60|0;t=a+44|0;b=2;for(f=f+c|0;;){d[2]|0?(Rd(1,a|0),d[m>>2]=d[w>>2],d[m+4>>2]=e,d[m+8>>2]=b,k=q(Vc(146,m|0)|0)|0,Sd(0)):(d[v>>2]=d[w>>2],d[v+4>>2]=e,d[v+8>>2]=b,k=q(Vc(146,
v|0)|0)|0);if((f|0)==(k|0)){f=6;break}if(0>(k|0)){f=8;break}f=f-k|0;g=d[e+4>>2]|0;k>>>0<=g>>>0?2==(b|0)?(d[r>>2]=(d[r>>2]|0)+k,l=g,b=2):l=g:(l=d[t>>2]|0,d[r>>2]=l,d[x>>2]=l,l=d[e+12>>2]|0,k=k-g|0,e=e+8|0,b=b+-1|0);d[e>>2]=(d[e>>2]|0)+k;d[e+4>>2]=l-k}6==(f|0)?(v=d[t>>2]|0,d[a+16>>2]=v+(d[a+48>>2]|0),a=v,d[r>>2]=a,d[x>>2]=a):8==(f|0)&&(d[a+16>>2]=0,d[r>>2]=0,d[x>>2]=0,d[a>>2]|=32,c=2==(b|0)?0:c-(d[e+4>>2]|0)|0);D=A;return c|0}function r(a){a=a|0;var b=0,c=0,e=0,f=0,g=0,k=0,b=a+20|0,g=a+28|0;(d[b>>2]|
0)>>>0>(d[g>>2]|0)>>>0&&(Ca[d[a+36>>2]&3](a,0,0)|0,0==(d[b>>2]|0))?b=-1:(k=a+4|0,c=d[k>>2]|0,e=a+8|0,f=d[e>>2]|0,c>>>0<f>>>0&&Ca[d[a+40>>2]&3](a,c-f|0,1)|0,d[a+16>>2]=0,d[g>>2]=0,d[b>>2]=0,d[e>>2]=0,b=d[k>>2]=0);return b|0}function J(a){a=a|0;var b=0,c=0,e=0,f=0,g=0,k=0,m=0,w=0,K=0,r=0,v=0,q=0,x=0,A=0,B=0,E=0,D=0,Da=0,C=0,L=0,y=0,J=0,I=0,R=0,S=0,V=0,W=0,Z=0,la=0,Ca=0,Fa=0,xb=0,db=0,Q=0,P=0,H=0,n=0;do if(245>a>>>0){x=11>a>>>0?16:a+11&-8;a=x>>>3;m=d[43]|0;c=m>>>a;if(c&3)return a=(c&1^1)+a|0,e=a<<1,
c=212+(e<<2)|0,e=212+(e+2<<2)|0,f=d[e>>2]|0,g=f+8|0,k=d[g>>2]|0,(c|0)!=(k|0)?(k>>>0<(d[47]|0)>>>0&&t(),b=k+12|0,(d[b>>2]|0)==(f|0)?(d[b>>2]=c,d[e>>2]=k):t()):d[43]=m&~(1<<a),n=a<<3,d[f+4>>2]=n|3,n=f+(n|4)|0,d[n>>2]|=1,n=g,n|0;k=d[45]|0;if(x>>>0>k>>>0){if(c)return e=2<<a,e=c<<a&(e|0-e),e=(e&0-e)+-1|0,w=e>>>12&16,e>>>=w,f=e>>>5&8,e>>>=f,g=e>>>2&4,e>>>=g,c=e>>>1&2,e>>>=c,a=e>>>1&1,a=(f|w|g|c|a)+(e>>>a)|0,e=a<<1,c=212+(e<<2)|0,e=212+(e+2<<2)|0,g=d[e>>2]|0,w=g+8|0,f=d[w>>2]|0,(c|0)!=(f|0)?(f>>>0<(d[47]|
0)>>>0&&t(),b=f+12|0,(d[b>>2]|0)==(g|0)?(d[b>>2]=c,d[e>>2]=f,K=d[45]|0):t()):(d[43]=m&~(1<<a),K=k),n=a<<3,k=n-x|0,d[g+4>>2]=x|3,m=g+x|0,d[g+(x|4)>>2]=k|1,d[g+n>>2]=k,K&&(f=d[48]|0,c=K>>>3,b=c<<1,e=212+(b<<2)|0,a=d[43]|0,c=1<<c,a&c?(a=212+(b+2<<2)|0,b=d[a>>2]|0,b>>>0<(d[47]|0)>>>0?t():(r=a,v=b)):(d[43]=a|c,r=212+(b+2<<2)|0,v=e),d[r>>2]=f,d[v+12>>2]=f,d[f+8>>2]=v,d[f+12>>2]=e),d[45]=k,d[48]=m,n=w,n|0;if(a=d[44]|0){c=(a&0-a)+-1|0;H=c>>>12&16;c>>>=H;P=c>>>5&8;c>>>=P;n=c>>>2&4;c>>>=n;a=c>>>1&2;c>>>=a;
e=c>>>1&1;e=d[476+((P|H|n|a|e)+(c>>>e)<<2)>>2]|0;c=(d[e+4>>2]&-8)-x|0;for(a=e;;){b=d[a+16>>2]|0;if(!b&&(b=d[a+20>>2]|0,!b)){w=c;break}a=(d[b+4>>2]&-8)-x|0;c=(n=a>>>0<c>>>0)?a:c;a=b;e=n?b:e}g=d[47]|0;e>>>0<g>>>0&&t();m=e+x|0;e>>>0>=m>>>0&&t();k=d[e+24>>2]|0;c=d[e+12>>2]|0;do if((c|0)==(e|0)){a=e+20|0;b=d[a>>2]|0;if(!b&&(a=e+16|0,b=d[a>>2]|0,!b)){q=0;break}for(;;)if(c=b+20|0,f=d[c>>2]|0)b=f,a=c;else if(c=b+16|0,f=d[c>>2]|0)b=f,a=c;else break;a>>>0<g>>>0?t():(d[a>>2]=0,q=b)}else f=d[e+8>>2]|0,f>>>0<
g>>>0&&t(),b=f+12|0,(d[b>>2]|0)!=(e|0)&&t(),a=c+8|0,(d[a>>2]|0)==(e|0)?(d[b>>2]=c,d[a>>2]=f,q=c):t();while(0);do if(k){b=d[e+28>>2]|0;a=476+(b<<2)|0;if((e|0)==(d[a>>2]|0)){if(d[a>>2]=q,!q){d[44]&=~(1<<b);break}}else if(k>>>0<(d[47]|0)>>>0&&t(),b=k+16|0,(d[b>>2]|0)==(e|0)?d[b>>2]=q:d[k+20>>2]=q,!q)break;a=d[47]|0;q>>>0<a>>>0&&t();d[q+24>>2]=k;if(b=d[e+16>>2]|0)b>>>0<a>>>0?t():(d[q+16>>2]=b,d[b+24>>2]=q);if(b=d[e+20>>2]|0)b>>>0<(d[47]|0)>>>0?t():(d[q+20>>2]=b,d[b+24>>2]=q)}while(0);if(16>w>>>0)n=w+
x|0,d[e+4>>2]=n|3,n=e+(n+4)|0,d[n>>2]|=1;else{d[e+4>>2]=x|3;d[e+(x|4)>>2]=w|1;d[e+(w+x)>>2]=w;if(b=d[45]|0)g=d[48]|0,c=b>>>3,b=c<<1,f=212+(b<<2)|0,a=d[43]|0,c=1<<c,a&c?(b=212+(b+2<<2)|0,a=d[b>>2]|0,a>>>0<(d[47]|0)>>>0?t():(A=b,B=a)):(d[43]=a|c,A=212+(b+2<<2)|0,B=f),d[A>>2]=g,d[B+12>>2]=g,d[g+8>>2]=B,d[g+12>>2]=f;d[45]=w;d[48]=m}n=e+8|0;return n|0}}B=x}else if(4294967231>=a>>>0){a=a+11|0;v=a&-8;if(r=d[44]|0){c=0-v|0;(a>>>=8)?16777215<v>>>0?K=31:(B=(a+1048320|0)>>>16&8,L=a<<B,A=(L+520192|0)>>>16&4,
L<<=A,K=(L+245760|0)>>>16&2,K=14-(A|B|K)+(L<<K>>>15)|0,K=v>>>(K+7|0)&1|K<<1):K=0;a=d[476+(K<<2)>>2]|0;a:do if(a)for(k=c,f=0,m=v<<(31==(K|0)?0:25-(K>>>1)|0),w=a,a=0;;){g=d[w+4>>2]&-8;c=g-v|0;if(c>>>0<k>>>0)if((g|0)==(v|0)){a=g=w;L=90;break a}else a=w;else c=k;L=d[w+20>>2]|0;w=d[w+16+(m>>>31<<2)>>2]|0;f=0==(L|0)|(L|0)==(w|0)?f:L;if(w)k=c,m<<=1;else{L=86;break}}else a=f=0,L=86;while(0);if(86==(L|0)){if(0==(f|0)&0==(a|0)){a=2<<K;a=r&(a|0-a);if(!a){B=v;break}a=(a&0-a)+-1|0;q=a>>>12&16;a>>>=q;r=a>>>5&8;
a>>>=r;A=a>>>2&4;a>>>=A;B=a>>>1&2;a>>>=B;f=a>>>1&1;f=d[476+((r|q|A|B|f)+(a>>>f)<<2)>>2]|0;a=0}f?(g=f,L=90):(m=c,w=a)}if(90==(L|0))for(;;)if(L=0,B=(d[g+4>>2]&-8)-v|0,c=(f=B>>>0<c>>>0)?B:c,a=f?g:a,f=d[g+16>>2]|0)g=f;else if(g=d[g+20>>2]|0,!g){m=c;w=a;break}if(0!=(w|0)&&m>>>0<((d[45]|0)-v|0)>>>0){f=d[47]|0;w>>>0<f>>>0&&t();k=w+v|0;w>>>0>=k>>>0&&t();g=d[w+24>>2]|0;c=d[w+12>>2]|0;do if((c|0)==(w|0)){a=w+20|0;b=d[a>>2]|0;if(!b&&(a=w+16|0,b=d[a>>2]|0,!b)){x=0;break}for(;;)if(c=b+20|0,e=d[c>>2]|0)b=e,a=c;
else if(c=b+16|0,e=d[c>>2]|0)b=e,a=c;else break;a>>>0<f>>>0?t():(d[a>>2]=0,x=b)}else e=d[w+8>>2]|0,e>>>0<f>>>0&&t(),b=e+12|0,(d[b>>2]|0)!=(w|0)&&t(),a=c+8|0,(d[a>>2]|0)==(w|0)?(d[b>>2]=c,d[a>>2]=e,x=c):t();while(0);do if(g){b=d[w+28>>2]|0;a=476+(b<<2)|0;if((w|0)==(d[a>>2]|0)){if(d[a>>2]=x,!x){d[44]&=~(1<<b);break}}else if(g>>>0<(d[47]|0)>>>0&&t(),b=g+16|0,(d[b>>2]|0)==(w|0)?d[b>>2]=x:d[g+20>>2]=x,!x)break;a=d[47]|0;x>>>0<a>>>0&&t();d[x+24>>2]=g;if(b=d[w+16>>2]|0)b>>>0<a>>>0?t():(d[x+16>>2]=b,d[b+
24>>2]=x);if(b=d[w+20>>2]|0)b>>>0<(d[47]|0)>>>0?t():(d[x+20>>2]=b,d[b+24>>2]=x)}while(0);a:do if(16<=m>>>0)if(d[w+4>>2]=v|3,d[w+(v|4)>>2]=m|1,d[w+(m+v)>>2]=m,b=m>>>3,256>m>>>0)a=b<<1,e=212+(a<<2)|0,c=d[43]|0,b=1<<b,c&b?(b=212+(a+2<<2)|0,a=d[b>>2]|0,a>>>0<(d[47]|0)>>>0?t():(D=b,Da=a)):(d[43]=c|b,D=212+(a+2<<2)|0,Da=e),d[D>>2]=k,d[Da+12>>2]=k,d[w+(v+8)>>2]=Da,d[w+(v+12)>>2]=e;else if((b=m>>>8)?16777215<m>>>0?e=31:(H=(b+1048320|0)>>>16&8,n=b<<H,P=(n+520192|0)>>>16&4,n<<=P,e=(n+245760|0)>>>16&2,e=14-
(P|H|e)+(n<<e>>>15)|0,e=m>>>(e+7|0)&1|e<<1):e=0,b=476+(e<<2)|0,d[w+(v+28)>>2]=e,d[w+(v+20)>>2]=0,d[w+(v+16)>>2]=0,a=d[44]|0,c=1<<e,a&c){b=d[b>>2]|0;b:do if((d[b+4>>2]&-8|0)!=(m|0)){for(e=m<<(31==(e|0)?0:25-(e>>>1)|0);;){a=b+16+(e>>>31<<2)|0;c=d[a>>2]|0;if(!c)break;if((d[c+4>>2]&-8|0)==(m|0)){I=c;break b}else e<<=1,b=c}if(a>>>0<(d[47]|0)>>>0)t();else{d[a>>2]=k;d[w+(v+24)>>2]=b;d[w+(v+12)>>2]=k;d[w+(v+8)>>2]=k;break a}}else I=b;while(0);b=I+8|0;a=d[b>>2]|0;n=d[47]|0;a>>>0>=n>>>0&I>>>0>=n>>>0?(d[a+12>>
2]=k,d[b>>2]=k,d[w+(v+8)>>2]=a,d[w+(v+12)>>2]=I,d[w+(v+24)>>2]=0):t()}else d[44]=a|c,d[b>>2]=k,d[w+(v+24)>>2]=b,d[w+(v+12)>>2]=k,d[w+(v+8)>>2]=k;else n=m+v|0,d[w+4>>2]=n|3,n=w+(n+4)|0,d[n>>2]|=1;while(0);n=w+8|0;return n|0}}B=v}else B=-1;while(0);c=d[45]|0;if(c>>>0>=B>>>0)return b=c-B|0,a=d[48]|0,15<b>>>0?(d[48]=a+B,d[45]=b,d[a+(B+4)>>2]=b|1,d[a+c>>2]=b,d[a+4>>2]=B|3):(d[45]=0,d[48]=0,d[a+4>>2]=c|3,n=a+(c+4)|0,d[n>>2]|=1),a+8|0;a=d[46]|0;if(a>>>0>B>>>0)return H=a-B|0,d[46]=H,n=d[49]|0,d[49]=n+B,d[n+
(B+4)>>2]=H|1,d[n+4>>2]=B|3,n=n+8|0,n|0;d[161]|0||(a=Td(30)|0,a+-1&a?t():(d[163]=a,d[162]=a,d[164]=-1,d[165]=-1,d[166]=0,d[154]=0,d[161]=(Ud(0)|0)&-16^1431655768));w=B+48|0;m=d[163]|0;K=B+47|0;k=m+K|0;m=0-m|0;r=k&m;if(r>>>0<=B>>>0)return 0;a=d[153]|0;if(0!=(a|0)&&(Da=d[151]|0,I=Da+r|0,I>>>0<=Da>>>0|I>>>0>a>>>0))return 0;a:do{if(d[154]&4)a=0;else{a=d[49]|0;b:do if(a){for(f=620;;){c=d[f>>2]|0;if(c>>>0<=a>>>0&&(E=f+4|0,(c+(d[E>>2]|0)|0)>>>0>a>>>0)){g=f;a=E;break}f=d[f+8>>2]|0;if(!f){L=174;break b}}c=
k-(d[46]|0)&m;if(2147483647>c>>>0)if(f=Ea(c|0)|0,a=(I=(f|0)==((d[g>>2]|0)+(d[a>>2]|0)|0))?c:0,I){if(-1!=(f|0)){y=f;A=a;L=194;break a}}else L=184;else a=0}else L=174;while(0);do if(174==(L|0))if(g=Ea(0)|0,-1!=(g|0))if(a=g,c=d[162]|0,f=c+-1|0,c=f&a?r-a+(f+a&0-c)|0:r,a=d[151]|0,f=a+c|0,c>>>0>B>>>0&2147483647>c>>>0)if(I=d[153]|0,0!=(I|0)&&f>>>0<=a>>>0|f>>>0>I>>>0)a=0;else if(f=Ea(c|0)|0,a=(I=(f|0)==(g|0))?c:0,I){y=g;A=a;L=194;break a}else L=184;else a=0;else a=0;while(0);b:do if(184==(L|0)){g=0-c|0;do if(w>>>
0>c>>>0&2147483647>c>>>0&-1!=(f|0)&&(C=d[163]|0,C=K-c+C&0-C,2147483647>C>>>0))if(-1==(Ea(C|0)|0)){Ea(g|0)|0;break b}else c=C+c|0;while(0);if(-1!=(f|0)){y=f;A=c;L=194;break a}}while(0);d[154]|=4}L=191}while(0);191==(L|0)&&2147483647>r>>>0&&(y=Ea(r|0)|0,J=Ea(0)|0,y>>>0<J>>>0&-1!=(y|0)&-1!=(J|0))&&(R=J-y|0,S=R>>>0>(B+40|0)>>>0,S)&&(A=S?R:a,L=194);if(194==(L|0)){a=(d[151]|0)+A|0;d[151]=a;a>>>0>(d[152]|0)>>>0&&(d[152]=a);k=d[49]|0;a:do if(k){g=620;do{a=d[g>>2]|0;c=g+4|0;f=d[c>>2]|0;if((y|0)==(a+f|0)){V=
a;W=c;Z=f;la=g;L=204;break}g=d[g+8>>2]|0}while(0!=(g|0));if(204==(L|0)&&0==(d[la+12>>2]&8|0)&&k>>>0<y>>>0&k>>>0>=V>>>0)d[W>>2]=Z+A,n=(d[46]|0)+A|0,H=k+8|0,H=0==(H&7|0)?0:0-H&7,P=n-H|0,d[49]=k+H,d[46]=P,d[k+(H+4)>>2]=P|1,d[k+(n+4)>>2]=40,d[50]=d[165];else{a=d[47]|0;y>>>0<a>>>0&&(a=d[47]=y);c=y+A|0;for(g=620;;){if((d[g>>2]|0)==(c|0)){c=f=g;L=212;break}g=d[g+8>>2]|0;if(!g){c=620;break}}if(212==(L|0))if(d[c+12>>2]&8)c=620;else{d[f>>2]=y;q=c+4|0;d[q>>2]=(d[q>>2]|0)+A;q=y+8|0;q=0==(q&7|0)?0:0-q&7;K=y+(A+
8)|0;K=0==(K&7|0)?0:0-K&7;b=y+(K+A)|0;v=q+B|0;x=y+v|0;r=b-(y+q)-B|0;d[y+(q+4)>>2]=B|3;b:do if((b|0)!=(k|0))if((b|0)==(d[48]|0))n=(d[45]|0)+r|0,d[45]=n,d[48]=x,d[y+(v+4)>>2]=n|1,d[y+(n+v)>>2]=n;else{m=A+4|0;c=d[y+(m+K)>>2]|0;if(1==(c&3|0)){w=c&-8;g=c>>>3;c:do if(256<=c>>>0){k=d[y+((K|24)+A)>>2]|0;e=d[y+(A+12+K)>>2]|0;do if((e|0)==(b|0)){f=K|16;e=y+(m+f)|0;c=d[e>>2]|0;if(!c&&(e=y+(f+A)|0,c=d[e>>2]|0,!c)){Q=0;break}for(;;)if(f=c+20|0,g=d[f>>2]|0)c=g,e=f;else if(f=c+16|0,g=d[f>>2]|0)c=g,e=f;else break;
e>>>0<a>>>0?t():(d[e>>2]=0,Q=c)}else f=d[y+((K|8)+A)>>2]|0,f>>>0<a>>>0&&t(),a=f+12|0,(d[a>>2]|0)!=(b|0)&&t(),c=e+8|0,(d[c>>2]|0)==(b|0)?(d[a>>2]=e,d[c>>2]=f,Q=e):t();while(0);if(k){a=d[y+(A+28+K)>>2]|0;c=476+(a<<2)|0;do if((b|0)!=(d[c>>2]|0)){if(k>>>0<(d[47]|0)>>>0&&t(),a=k+16|0,(d[a>>2]|0)==(b|0)?d[a>>2]=Q:d[k+20>>2]=Q,!Q)break c}else if(d[c>>2]=Q,!Q){d[44]&=~(1<<a);break c}while(0);c=d[47]|0;Q>>>0<c>>>0&&t();d[Q+24>>2]=k;b=K|16;if(a=d[y+(b+A)>>2]|0)a>>>0<c>>>0?t():(d[Q+16>>2]=a,d[a+24>>2]=Q);if(b=
d[y+(m+b)>>2]|0)b>>>0<(d[47]|0)>>>0?t():(d[Q+20>>2]=b,d[b+24>>2]=Q)}}else e=d[y+((K|8)+A)>>2]|0,f=d[y+(A+12+K)>>2]|0,c=212+(g<<1<<2)|0,(e|0)!=(c|0)&&(e>>>0<a>>>0&&t(),(d[e+12>>2]|0)!=(b|0)&&t()),(f|0)==(e|0)?d[43]&=~(1<<g):((f|0)==(c|0)?Ca=f+8|0:(f>>>0<a>>>0&&t(),a=f+8|0,(d[a>>2]|0)==(b|0)?Ca=a:t()),d[e+12>>2]=f,d[Ca>>2]=e);while(0);b=y+((w|K)+A)|0;f=w+r|0}else f=r;b=b+4|0;d[b>>2]&=-2;d[y+(v+4)>>2]=f|1;d[y+(f+v)>>2]=f;b=f>>>3;if(256>f>>>0)a=b<<1,e=212+(a<<2)|0,c=d[43]|0,b=1<<b,c&b?(b=212+(a+2<<2)|
0,a=d[b>>2]|0,a>>>0>=(d[47]|0)>>>0?(P=b,H=a):t()):(d[43]=c|b,P=212+(a+2<<2)|0,H=e),d[P>>2]=x,d[H+12>>2]=x,d[y+(v+8)>>2]=H,d[y+(v+12)>>2]=e;else if((b=f>>>8)?16777215<f>>>0?e=31:(P=(b+1048320|0)>>>16&8,H=b<<P,Q=(H+520192|0)>>>16&4,H<<=Q,e=(H+245760|0)>>>16&2,e=14-(Q|P|e)+(H<<e>>>15)|0,e=f>>>(e+7|0)&1|e<<1):e=0,b=476+(e<<2)|0,d[y+(v+28)>>2]=e,d[y+(v+20)>>2]=0,d[y+(v+16)>>2]=0,a=d[44]|0,c=1<<e,a&c){b=d[b>>2]|0;c:do if((d[b+4>>2]&-8|0)!=(f|0)){for(e=f<<(31==(e|0)?0:25-(e>>>1)|0);;){a=b+16+(e>>>31<<2)|
0;c=d[a>>2]|0;if(!c)break;if((d[c+4>>2]&-8|0)==(f|0)){n=c;break c}else e<<=1,b=c}if(a>>>0<(d[47]|0)>>>0)t();else{d[a>>2]=x;d[y+(v+24)>>2]=b;d[y+(v+12)>>2]=x;d[y+(v+8)>>2]=x;break b}}else n=b;while(0);b=n+8|0;a=d[b>>2]|0;H=d[47]|0;a>>>0>=H>>>0&n>>>0>=H>>>0?(d[a+12>>2]=x,d[b>>2]=x,d[y+(v+8)>>2]=a,d[y+(v+12)>>2]=n,d[y+(v+24)>>2]=0):t()}else d[44]=a|c,d[b>>2]=x,d[y+(v+24)>>2]=b,d[y+(v+12)>>2]=x,d[y+(v+8)>>2]=x}else n=(d[46]|0)+r|0,d[46]=n,d[49]=x,d[y+(v+4)>>2]=n|1;while(0);n=y+(q|8)|0;return n|0}for(;;){a=
d[c>>2]|0;if(a>>>0<=k>>>0&&(b=d[c+4>>2]|0,e=a+b|0,e>>>0>k>>>0))break;c=d[c+8>>2]|0}f=a+(b+-39)|0;a=a+(b+-47+(0==(f&7|0)?0:0-f&7))|0;f=k+16|0;a=a>>>0<f>>>0?k:a;b=a+8|0;c=y+8|0;c=0==(c&7|0)?0:0-c&7;n=A+-40-c|0;d[49]=y+c;d[46]=n;d[y+(c+4)>>2]=n|1;d[y+(A+-36)>>2]=40;d[50]=d[165];c=a+4|0;d[c>>2]=27;d[b>>2]=d[155];d[b+4>>2]=d[156];d[b+8>>2]=d[157];d[b+12>>2]=d[158];d[155]=y;d[156]=A;d[158]=0;d[157]=b;b=a+28|0;d[b>>2]=7;if((a+32|0)>>>0<e>>>0){do n=b,b=b+4|0,d[b>>2]=7;while((n+8|0)>>>0<e>>>0)}if((a|0)!=(k|
0))if(g=a-k|0,d[c>>2]&=-2,d[k+4>>2]=g|1,d[a>>2]=g,b=g>>>3,256>g>>>0)a=b<<1,e=212+(a<<2)|0,c=d[43]|0,b=1<<b,c&b?(b=212+(a+2<<2)|0,a=d[b>>2]|0,a>>>0<(d[47]|0)>>>0?t():(Fa=b,xb=a)):(d[43]=c|b,Fa=212+(a+2<<2)|0,xb=e),d[Fa>>2]=k,d[xb+12>>2]=k,d[k+8>>2]=xb,d[k+12>>2]=e;else if((b=g>>>8)?16777215<g>>>0?e=31:(H=(b+1048320|0)>>>16&8,n=b<<H,P=(n+520192|0)>>>16&4,n<<=P,e=(n+245760|0)>>>16&2,e=14-(P|H|e)+(n<<e>>>15)|0,e=g>>>(e+7|0)&1|e<<1):e=0,c=476+(e<<2)|0,d[k+28>>2]=e,d[k+20>>2]=0,d[f>>2]=0,b=d[44]|0,a=1<<
e,b&a){b=d[c>>2]|0;b:do if((d[b+4>>2]&-8|0)!=(g|0)){for(e=g<<(31==(e|0)?0:25-(e>>>1)|0);;){a=b+16+(e>>>31<<2)|0;c=d[a>>2]|0;if(!c)break;if((d[c+4>>2]&-8|0)==(g|0)){db=c;break b}else e<<=1,b=c}if(a>>>0<(d[47]|0)>>>0)t();else{d[a>>2]=k;d[k+24>>2]=b;d[k+12>>2]=k;d[k+8>>2]=k;break a}}else db=b;while(0);b=db+8|0;a=d[b>>2]|0;n=d[47]|0;a>>>0>=n>>>0&db>>>0>=n>>>0?(d[a+12>>2]=k,d[b>>2]=k,d[k+8>>2]=a,d[k+12>>2]=db,d[k+24>>2]=0):t()}else d[44]=b|a,d[c>>2]=k,d[k+24>>2]=c,d[k+12>>2]=k,d[k+8>>2]=k}}else{n=d[47]|
0;0==(n|0)|y>>>0<n>>>0&&(d[47]=y);d[155]=y;d[156]=A;d[158]=0;d[52]=d[161];d[51]=-1;b=0;do n=b<<1,H=212+(n<<2)|0,d[212+(n+3<<2)>>2]=H,d[212+(n+2<<2)>>2]=H,b=b+1|0;while(32!=(b|0));n=y+8|0;n=0==(n&7|0)?0:0-n&7;H=A+-40-n|0;d[49]=y+n;d[46]=H;d[y+(n+4)>>2]=H|1;d[y+(A+-36)>>2]=40;d[50]=d[165]}while(0);b=d[46]|0;if(b>>>0>B>>>0)return H=b-B|0,d[46]=H,n=d[49]|0,d[49]=n+B,d[n+(B+4)>>2]=H|1,d[n+4>>2]=B|3,n=n+8|0,n|0}d[(l()|0)>>2]=12;return 0}function I(a,b,c,d){a=a|0;c=a+(c|0)>>>0;return(la=(b|0)+(d|0)+(c>>>
0<a>>>0|0)>>>0,c|0)|0}function R(a,b,c){a=a|0;b=b|0;c=c|0;var e=0;if(4096<=(c|0))return Vd(a|0,b|0,c|0)|0;e=a|0;if((a&3)==(b&3)){for(;a&3;){if(!c)return e|0;Z[a>>0]=Z[b>>0]|0;a=a+1|0;b=b+1|0;c=c-1|0}for(;4<=(c|0);)d[a>>2]=d[b>>2],a=a+4|0,b=b+4|0,c=c-4|0}for(;0<(c|0);)Z[a>>0]=Z[b>>0]|0,a=a+1|0,b=b+1|0,c=c-1|0;return e|0}function S(a,b,c){a=a|0;b=b|0;c=c|0;var d=0;if((b|0)<(a|0)&(a|0)<(b+c|0)){d=a;b=b+c|0;for(a=a+c|0;0<(c|0);)a=a-1|0,b=b-1|0,c=c-1|0,Z[a>>0]=Z[b>>0]|0;a=d}else R(a,b,c)|0;return a|0}
"almost asm";var Z=new a.Int8Array(c);new a.Int16Array(c);var d=new a.Int32Array(c),V=new a.Uint8Array(c),W=new a.Uint16Array(c);new a.Uint32Array(c);new a.Float32Array(c);new a.Float64Array(c);var D=b.STACKTOP|0,Wc=0,la=0,Fa=b.abort,Sd=b._pthread_cleanup_pop,Pd=b.___lock,Od=b._pthread_self,t=b._abort,Wd=b.___syscall6,Ea=b._sbrk,Ud=b._time,Vd=b._emscripten_memcpy_big,Xd=b.___syscall54,Qd=b.___unlock,Yd=b.___syscall140,Rd=b._pthread_cleanup_push,Td=b._sysconf,Vc=b.___syscall146,Zd=[function(){Fa(0);
return 0},function(a){var b=0,c=0,b=D;D=D+16|0;c=b;d[c>>2]=d[(a|0)+60>>2];a=q(Wd(6,c|0)|0)|0;D=b;return a|0}],Ca=[function(){Fa(1);return 0},function(a,b,c){a=a|0;b=b|0;c=c|0;var e=0,f=0,f=D;D=D+80|0;e=f;d[a+36>>2]=3;0==(d[a>>2]&64|0)&&(d[e>>2]=d[a+60>>2],d[e+4>>2]=21505,d[e+8>>2]=f+12,0!=(Xd(54,e|0)|0))&&(Z[a+75>>0]=-1);e=E(a,b,c)|0;D=f;return e|0},function(a,b,c){var e=0,f=0,g=0,f=D;D=D+32|0;g=f;e=f+20|0;d[g>>2]=d[(a|0)+60>>2];d[g+4>>2]=0;d[g+8>>2]=b|0;d[g+12>>2]=e;d[g+16>>2]=c|0;a=0>(q(Yd(140,
g|0)|0)|0)?d[e>>2]=-1:d[e>>2]|0;D=f;return a|0},E],$d=[function(){Fa(2)},function(){}];return{_malloc:J,_fflush:m,_i64Add:I,_memmove:S,_memset:function(a,b,c){a=a|0;b=b|0;c=c|0;var e=0,f=0,g=0,k=0,e=a+c|0;if(20<=(c|0)){b&=255;g=a&3;k=b|b<<8|b<<16|b<<24;f=e&-4;if(g)for(g=a+4-g|0;(a|0)<(g|0);)Z[a>>0]=b,a=a+1|0;for(;(a|0)<(f|0);)d[a>>2]=k,a=a+4|0}for(;(a|0)<(e|0);)Z[a>>0]=b,a=a+1|0;return a-c|0},_zuc_generate_keystream:function(a,b,c,k){a=a|0;b=b|0;c=c|0;k=k|0;var l=0,m=0,t=0,q=0;e(a);f(a)|0;g(a);t=
a+84|0;if(!(0==(c|0)&0==(k|0))){m=l=0;do e(a),q=f(a)|0,d[b+(l<<2)>>2]=d[t>>2]^q,g(a),l=I(l|0,m|0,1,0)|0,m=la;while(m>>>0<k>>>0|(m|0)==(k|0)&l>>>0<c>>>0)}},_zuc_init:function(a,b,c){a=a|0;b=b|0;c=c|0;var g=0,l=0,m=0;a||(a=J(88)|0);l=g=0;do d[a+(l<<2)>>2]=(W[668+(l<<1)>>1]|0)<<8|(V[b+l>>0]|0)<<23|V[c+l>>0]|0,l=I(l|0,g|0,1,0)|0,g=la;while(0>g>>>0|0==(g|0)&16>l>>>0);g=a+64|0;d[g>>2]=0;d[g+4>>2]=0;g=a+4|0;l=a+60|0;b=c=0;do e(a),m=(f(a)|0)>>>1,m=(k(a)|0)+m|0,S(a|0,g|0,60)|0,d[l>>2]=(m&2147483647)+(m>>>
31),c=I(c|0,b|0,1,0)|0,b=la;while(0>b>>>0|0==(b|0)&32>c>>>0);return a|0},_memcpy:R,_free:function(a){a=a|0;var b=0,c=0,e=0,f=0,g=0,k=0,l=0,m=0,q=0,r=0,v=0,E=0,x=0,A=0,B=0,I=0,D=0,J=0,C=0;if(a){b=a+-8|0;l=d[47]|0;b>>>0<l>>>0&&t();c=d[a+-4>>2]|0;e=c&3;1==(e|0)&&t();x=c&-8;B=a+(x+-8)|0;do if(c&1)C=b,g=x;else{b=d[b>>2]|0;if(!e)return;m=-8-b|0;r=a+m|0;v=b+x|0;r>>>0<l>>>0&&t();if((r|0)==(d[48]|0)){b=a+(x+-4)|0;c=d[b>>2]|0;if(3!=(c&3|0)){C=r;g=v;break}d[45]=v;d[b>>2]=c&-2;d[a+(m+4)>>2]=v|1;d[B>>2]=v;return}f=
b>>>3;if(256>b>>>0)e=d[a+(m+8)>>2]|0,c=d[a+(m+12)>>2]|0,b=212+(f<<1<<2)|0,(e|0)!=(b|0)&&(e>>>0<l>>>0&&t(),(d[e+12>>2]|0)!=(r|0)&&t()),(c|0)==(e|0)?d[43]&=~(1<<f):((c|0)!=(b|0)?(c>>>0<l>>>0&&t(),b=c+8|0,(d[b>>2]|0)==(r|0)?k=b:t()):k=c+8|0,d[e+12>>2]=c,d[k>>2]=e),C=r,g=v;else{k=d[a+(m+24)>>2]|0;e=d[a+(m+12)>>2]|0;do if((e|0)==(r|0)){c=a+(m+20)|0;b=d[c>>2]|0;if(!b&&(c=a+(m+16)|0,b=d[c>>2]|0,!b)){q=0;break}for(;;)if(e=b+20|0,f=d[e>>2]|0)b=f,c=e;else if(e=b+16|0,f=d[e>>2]|0)b=f,c=e;else break;c>>>0<l>>>
0?t():(d[c>>2]=0,q=b)}else f=d[a+(m+8)>>2]|0,f>>>0<l>>>0&&t(),b=f+12|0,(d[b>>2]|0)!=(r|0)&&t(),c=e+8|0,(d[c>>2]|0)==(r|0)?(d[b>>2]=e,d[c>>2]=f,q=e):t();while(0);if(k){b=d[a+(m+28)>>2]|0;c=476+(b<<2)|0;if((r|0)==(d[c>>2]|0)){if(d[c>>2]=q,!q){d[44]&=~(1<<b);C=r;g=v;break}}else if(k>>>0<(d[47]|0)>>>0&&t(),b=k+16|0,(d[b>>2]|0)==(r|0)?d[b>>2]=q:d[k+20>>2]=q,!q){C=r;g=v;break}c=d[47]|0;q>>>0<c>>>0&&t();d[q+24>>2]=k;if(b=d[a+(m+16)>>2]|0)b>>>0<c>>>0?t():(d[q+16>>2]=b,d[b+24>>2]=q);(b=d[a+(m+20)>>2]|0)?b>>>
0<(d[47]|0)>>>0?t():(d[q+20>>2]=b,d[b+24>>2]=q,C=r,g=v):(C=r,g=v)}else C=r,g=v}}while(0);C>>>0>=B>>>0&&t();b=a+(x+-4)|0;c=d[b>>2]|0;c&1||t();if(c&2)d[b>>2]=c&-2,d[C+4>>2]=g|1,d[C+g>>2]=g;else{if((B|0)==(d[49]|0)){J=(d[46]|0)+g|0;d[46]=J;d[49]=C;d[C+4>>2]=J|1;if((C|0)!=(d[48]|0))return;d[48]=0;d[45]=0;return}if((B|0)==(d[48]|0)){J=(d[45]|0)+g|0;d[45]=J;d[48]=C;d[C+4>>2]=J|1;d[C+J>>2]=J;return}g=(c&-8)+g|0;f=c>>>3;do if(256<=c>>>0){k=d[a+(x+16)>>2]|0;b=d[a+(x|4)>>2]|0;do if((b|0)==(B|0)){c=a+(x+12)|
0;b=d[c>>2]|0;if(!b&&(c=a+(x+8)|0,b=d[c>>2]|0,!b)){A=0;break}for(;;)if(e=b+20|0,f=d[e>>2]|0)b=f,c=e;else if(e=b+16|0,f=d[e>>2]|0)b=f,c=e;else break;c>>>0<(d[47]|0)>>>0?t():(d[c>>2]=0,A=b)}else c=d[a+x>>2]|0,c>>>0<(d[47]|0)>>>0&&t(),e=c+12|0,(d[e>>2]|0)!=(B|0)&&t(),f=b+8|0,(d[f>>2]|0)==(B|0)?(d[e>>2]=b,d[f>>2]=c,A=b):t();while(0);if(k){b=d[a+(x+20)>>2]|0;c=476+(b<<2)|0;if((B|0)==(d[c>>2]|0)){if(d[c>>2]=A,!A){d[44]&=~(1<<b);break}}else if(k>>>0<(d[47]|0)>>>0&&t(),b=k+16|0,(d[b>>2]|0)==(B|0)?d[b>>2]=
A:d[k+20>>2]=A,!A)break;c=d[47]|0;A>>>0<c>>>0&&t();d[A+24>>2]=k;if(b=d[a+(x+8)>>2]|0)b>>>0<c>>>0?t():(d[A+16>>2]=b,d[b+24>>2]=A);if(b=d[a+(x+12)>>2]|0)b>>>0<(d[47]|0)>>>0?t():(d[A+20>>2]=b,d[b+24>>2]=A)}}else e=d[a+x>>2]|0,c=d[a+(x|4)>>2]|0,b=212+(f<<1<<2)|0,(e|0)!=(b|0)&&(e>>>0<(d[47]|0)>>>0&&t(),(d[e+12>>2]|0)!=(B|0)&&t()),(c|0)==(e|0)?d[43]&=~(1<<f):((c|0)!=(b|0)?(c>>>0<(d[47]|0)>>>0&&t(),b=c+8|0,(d[b>>2]|0)==(B|0)?E=b:t()):E=c+8|0,d[e+12>>2]=c,d[E>>2]=e);while(0);d[C+4>>2]=g|1;d[C+g>>2]=g;if((C|
0)==(d[48]|0)){d[45]=g;return}}b=g>>>3;if(256>g>>>0)c=b<<1,f=212+(c<<2)|0,e=d[43]|0,b=1<<b,e&b?(b=212+(c+2<<2)|0,c=d[b>>2]|0,c>>>0<(d[47]|0)>>>0?t():(I=b,D=c)):(d[43]=e|b,I=212+(c+2<<2)|0,D=f),d[I>>2]=C,d[D+12>>2]=C,d[C+8>>2]=D,d[C+12>>2]=f;else{(b=g>>>8)?16777215<g>>>0?f=31:(I=(b+1048320|0)>>>16&8,D=b<<I,B=(D+520192|0)>>>16&4,D<<=B,f=(D+245760|0)>>>16&2,f=14-(B|I|f)+(D<<f>>>15)|0,f=g>>>(f+7|0)&1|f<<1):f=0;b=476+(f<<2)|0;d[C+28>>2]=f;d[C+20>>2]=0;d[C+16>>2]=0;c=d[44]|0;e=1<<f;a:do if(c&e){b=d[b>>
2]|0;b:do if((d[b+4>>2]&-8|0)!=(g|0)){for(f=g<<(31==(f|0)?0:25-(f>>>1)|0);;){c=b+16+(f>>>31<<2)|0;e=d[c>>2]|0;if(!e)break;if((d[e+4>>2]&-8|0)==(g|0)){J=e;break b}else f<<=1,b=e}if(c>>>0<(d[47]|0)>>>0)t();else{d[c>>2]=C;d[C+24>>2]=b;d[C+12>>2]=C;d[C+8>>2]=C;break a}}else J=b;while(0);b=J+8|0;c=d[b>>2]|0;D=d[47]|0;c>>>0>=D>>>0&J>>>0>=D>>>0?(d[c+12>>2]=C,d[b>>2]=C,d[C+8>>2]=c,d[C+12>>2]=J,d[C+24>>2]=0):t()}else d[44]=c|e,d[b>>2]=C,d[C+24>>2]=b,d[C+12>>2]=C,d[C+8>>2]=C;while(0);C=(d[51]|0)+-1|0;d[51]=
C;if(!C){for(b=628;;)if(b=d[b>>2]|0)b=b+8|0;else break;d[51]=-1}}}},___errno_location:l,runPostSets:function(){},stackAlloc:function(a){var b=0,b=D;D=D+(a|0)|0;D=D+15&-16;return b|0},stackSave:function(){return D|0},stackRestore:function(a){D=a|0},establishStackSpace:function(a){D=a|0},setThrew:function(a){Wc||(Wc=a|0)},setTempRet0:function(a){la=a|0},getTempRet0:function(){return la|0},dynCall_ii:function(a,b){return Zd[(a|0)&1](b|0)|0},dynCall_iiii:function(a,b,c,d){return Ca[(a|0)&3](b|0,c|0,d|
0)|0},dynCall_vi:function(a,b){$d[(a|0)&1](b|0)}}}(h.asmGlobalArg,h.asmLibraryArg,buffer);h._zuc_generate_keystream=Y._zuc_generate_keystream;h._fflush=Y._fflush;h.runPostSets=Y.runPostSets;var zb=h._i64Add=Y._i64Add,Mc=h._memmove=Y._memmove,Ab=h._memset=Y._memset,Na=h._malloc=Y._malloc;h._zuc_init=Y._zuc_init;var Lc=h._memcpy=Y._memcpy,Wa=h._free=Y._free;h.___errno_location=Y.___errno_location;h.dynCall_ii=Y.dynCall_ii;h.dynCall_iiii=Y.dynCall_iiii;h.dynCall_vi=Y.dynCall_vi;p.aa=Y.stackAlloc;
p.ua=Y.stackSave;p.ba=Y.stackRestore;p.zd=Y.establishStackSpace;p.pb=Y.setTempRet0;p.cb=Y.getTempRet0;
if(wb)if("function"===typeof h.locateFile?wb=h.locateFile(wb):h.memoryInitializerPrefixURL&&(wb=h.memoryInitializerPrefixURL+wb),ea||fa){var Fd=h.readBinary(wb);M.set(Fd,p.Ba)}else{var Hd=function(){Bd(wb,Gd,function(){throw"could not load memory initializer "+wb;})};ub();var Gd=function(a){a.byteLength&&(a=new Uint8Array(a));M.set(a,p.Ba);vb()},Id=h.memoryInitializerRequest;if(Id){var Jd=function(){200!==Id.status&&0!==Id.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
Id.status+", retrying "+wb),Hd()):Gd(Id.response)};Id.response?setTimeout(Jd,0):Id.addEventListener("load",Jd)}else Hd()}function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ja.prototype=Error();ja.prototype.constructor=ja;var Kd=null,tb=function Ld(){h.calledRun||Md();h.calledRun||(tb=Ld)};
h.callMain=h.wd=function(a){function b(){for(var a=0;3>a;a++)e.push(0)}assert(0==rb,"cannot call main when async dependencies remain! (listen on __ATMAIN__)");assert(0==jb.length,"cannot call main when preRun functions remain to be called");a=a||[];Qa||(Qa=!0,ib(kb));var c=a.length+1,e=[Ma(qb(h.thisProgram),"i8",0)];b();for(var f=0;f<c-1;f+=1)e.push(Ma(qb(a[f]),"i8",0)),b();e.push(0);e=Ma(e,"i32",0);try{var g=h._main(c,e,0);Nd(g,!0)}catch(k){if(!(k instanceof ja))if("SimulateInfiniteLoop"==k)h.noExitRuntime=
!0;else throw k&&"object"===typeof k&&k.stack&&h.W("exception thrown: "+[k,k.stack]),k;}finally{}};
function Md(a){function b(){if(!h.calledRun&&(h.calledRun=!0,!qa)){Qa||(Qa=!0,ib(kb));ib(lb);if(h.onRuntimeInitialized)h.onRuntimeInitialized();h._main&&ae&&h.callMain(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)pb(h.postRun.shift());ib(nb)}}a=a||h.arguments;null===Kd&&(Kd=Date.now());if(!(0<rb)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ob(h.preRun.shift());ib(jb);0<rb||h.calledRun||(h.setStatus?(h.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=h.run=Md;function Nd(a,b){if(!b||!h.noExitRuntime){if(!h.noExitRuntime&&(qa=!0,ma=void 0,ib(mb),h.onExit))h.onExit(a);ea?(process.stdout.once("drain",function(){process.exit(a)}),console.log(" "),setTimeout(function(){process.exit(a)},500)):fa&&"function"===typeof quit&&quit(a);throw new ja(a);}}h.exit=h.exit=Nd;var be=[];
function u(a){void 0!==a?(h.print(a),h.W(a),a=JSON.stringify(a)):a="";qa=!0;var b="abort("+a+") at "+Xa()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";be&&be.forEach(function(c){b=c(b,a)});throw b;}h.abort=h.abort=u;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ae=!0;h.noInitialRun&&(ae=!1);Md();
